use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

static NEXT_ID: AtomicU64 = AtomicU64::new(0);

fn unique_temp_dir() -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("time went backwards")
        .as_nanos();
    let id = NEXT_ID.fetch_add(1, Ordering::Relaxed);
    std::env::temp_dir().join(format!("sw-test-{}-{nanos}-{id}", std::process::id()))
}

fn prepare_workspace() -> PathBuf {
    let dir = unique_temp_dir();
    fs::create_dir_all(&dir).expect("failed to create temp dir");
    dir
}

fn run_in_dir(args: &[&str], dir: &Path) -> std::process::Output {
    Command::new(env!("CARGO_BIN_EXE_sw"))
        .args(args)
        .current_dir(dir)
        .output()
        .expect("failed to execute sw")
}

fn run_in_dir_with_env(args: &[&str], dir: &Path, envs: &[(&str, &Path)]) -> std::process::Output {
    let mut command = Command::new(env!("CARGO_BIN_EXE_sw"));
    command.args(args).current_dir(dir);
    for (key, value) in envs {
        command.env(key, value);
    }
    command.output().expect("failed to execute sw")
}

fn write_runbook(dir: &Path, fixture_name: &str, target_name: &str) -> PathBuf {
    let source = Path::new("tests/fixtures").join(fixture_name);
    let target = dir.join(target_name);
    let contents = fs::read_to_string(source).expect("failed to read fixture");
    fs::write(&target, contents).expect("failed to write fixture");
    target
}

fn create_fake_java_home(dir: &Path, folder_name: &str, version: &str) -> PathBuf {
    let java_home = dir.join(folder_name);
    let bin_dir = java_home.join("bin");
    fs::create_dir_all(&bin_dir).expect("failed to create fake java bin dir");
    let java_path = bin_dir.join("java");
    fs::write(
        &java_path,
        format!("#!/bin/sh\necho 'openjdk version \"{version}.0.1\"' >&2\necho 'Fake Java' >&2\n"),
    )
    .expect("failed to write fake java");
    #[cfg(unix)]
    {
        let mut permissions = fs::metadata(&java_path)
            .expect("missing fake java metadata")
            .permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(&java_path, permissions).expect("failed to make fake java executable");
    }
    java_home
}

fn write_text_file(dir: &Path, relative_path: &str, contents: &str) {
    let path = dir.join(relative_path);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("failed to create parent directory");
    }
    fs::write(path, contents).expect("failed to write text file");
}

#[test]
fn no_args_defaults_to_run_and_writes_readme() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-success.json", "sw-runbook.json");

    let output = run_in_dir(&[], &dir);

    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("Rendered runbook to README.md"));

    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.starts_with(
        "<!-- Generated by Sociable Weaver. Manual edits will be overwritten when regenerated. -->\n\n"
    ));
    assert!(readme.contains("# Runbook execution"));
    assert!(readme.contains("```shell"));
    assert!(readme.contains("```\nHello there\n```"));
    assert!(!readme.contains("```text\nfirst\n```"));
    assert_eq!(
        fs::read_to_string(dir.join("sequence.txt")).expect("missing command side effect"),
        "first\nsecond\n"
    );
}

#[test]
fn run_command_writes_requested_output_file() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-success.json", "example.json");

    let output = run_in_dir(
        &[
            "run",
            "--input-file",
            "example.json",
            "--output-format",
            "markdown",
            "--output-file",
            "custom.md",
        ],
        &dir,
    );

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("custom.md")).expect("missing custom output");
    assert!(readme.starts_with(
        "<!-- Generated by Sociable Weaver. Manual edits will be overwritten when regenerated. -->\n\n"
    ));
    assert!(readme.contains("Captured output"));
    assert!(readme.contains("```\nHello there\n```"));
    assert!(!readme.contains("```text\nfirst\n```"));
}

#[test]
fn verbose_run_reports_entry_progress_to_stderr() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-success.json", "sw-runbook.json");

    let output = run_in_dir(&["run", "--verbose"], &dir);

    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert_eq!(stdout.trim(), "Rendered runbook to README.md");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("[1/5] Heading: Runbook execution ("));
    assert!(
        stderr.contains("[2/5] Markdown: This runbook verifies command execution and rendering. (")
    );
    assert!(stderr.contains("[3/5] Command: printf 'first\\n' > sequence.txt ("));
    assert!(stderr.contains(" / 2m)"));
    assert!(!stderr.contains("...)"));
}

#[test]
fn verbose_flag_before_subcommand_uses_default_run_behavior() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-success.json", "sw-runbook.json");

    let output = run_in_dir(&["--verbose"], &dir);

    assert!(output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("[1/5] Heading: Runbook execution ("));
    assert!(stderr.contains("[5/5] Command: printf 'Hello there\\n' ("));
}

#[test]
fn debug_run_reports_rewrite_and_capture_diagnostics_to_stderr() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-rewrite-generated-capture-pair.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run", "--debug"], &dir);

    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert_eq!(stdout.trim(), "Rendered runbook to README.md");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("[debug] Command entry:"));
    assert!(stderr.contains("[debug] Raw stdout:"));
    assert!(stderr.contains("audio file> target/audio/audio_20260312_142351.mp3"));
    assert!(stderr.contains("[debug] Rewrite datetime_shift pattern: audio_\\d{8}_\\d{6}"));
    assert!(stderr.contains("[debug] Rewrite datetime_shift match count: 1"));
    assert!(stderr.contains("[debug] Rewritten stdout:"));
    assert!(stderr.contains("audio file> target/audio/audio_20770427_123456.mp3"));
    assert!(
        stderr.contains("[debug] Generated capture audio_path_1_original = audio_20260312_142351")
    );
    assert!(
        stderr.contains("[debug] Generated capture audio_path_1_rewritten = audio_20770427_123456")
    );
}

#[test]
fn debug_flag_before_subcommand_uses_default_run_behavior() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-rewrite-generated-capture-pair.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["--debug"], &dir);

    assert!(output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("[debug] Command entry:"));
    assert!(stderr.contains("[debug] Rewritten stdout:"));
}

#[test]
fn command_scoped_debug_only_emits_diagnostics_for_flagged_commands() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-command-scoped-debug.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert_eq!(stderr.matches("[debug] Command entry:").count(), 1);
    assert!(stderr.contains("beta"));
    assert!(!stderr.contains("alpha"));
}

#[test]
fn global_debug_still_emits_diagnostics_for_all_commands() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-command-scoped-debug.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run", "--debug"], &dir);

    assert!(output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert_eq!(stderr.matches("[debug] Command entry:").count(), 2);
    assert!(stderr.contains("alpha"));
    assert!(stderr.contains("beta"));
}

#[test]
fn generated_marker_appears_before_rendered_entries() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-success.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    let marker =
        "<!-- Generated by Sociable Weaver. Manual edits will be overwritten when regenerated. -->";
    assert!(readme.starts_with(marker));
    assert!(readme.contains(&format!("{marker}\n\n# Runbook execution")));
}

#[test]
fn patch_entry_applies_during_run_and_restores_after_success() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-patch-success.json", "sw-runbook.json");
    write_text_file(&dir, "demo.txt", "before\n");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme");
    assert!(readme.contains("```diff"));
    assert!(readme.contains("+after"));
    assert!(readme.contains("Patched file contents"));
    assert!(readme.contains("```\nafter\n```"));
    assert_eq!(
        fs::read_to_string(dir.join("demo.txt")).expect("missing restored file"),
        "before\n"
    );
}

#[test]
fn stacked_patch_entries_build_on_each_other_and_restore_original_file() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-patch-stacked.json", "sw-runbook.json");
    write_text_file(&dir, "demo.txt", "before\n");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme");
    assert!(readme.contains("Stacked patch contents"));
    assert!(readme.contains("```\nafter\n```"));
    assert_eq!(
        fs::read_to_string(dir.join("demo.txt")).expect("missing restored file"),
        "before\n"
    );
}

#[test]
fn patch_entry_restores_file_after_timeout() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-patch-timeout-restore.json",
        "sw-runbook.json",
    );
    write_text_file(&dir, "demo.txt", "before\n");

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert_eq!(
        fs::read_to_string(dir.join("demo.txt")).expect("missing restored file"),
        "before\n"
    );
}

#[test]
fn multiline_command_lines_share_the_same_shell_context() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-multiline.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("NAME='Albert Attard'\necho ${NAME}"));
    assert!(readme.contains("Name output"));
    assert!(readme.contains("```\nAlbert Attard\n```"));
}

#[test]
fn prerequisites_render_and_execute_before_main_workflow() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-prerequisites-success.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("## Prerequisites"));
    assert!(readme.contains("- Environment marker file"));
    assert!(readme.contains("Must be available before the main workflow runs."));
    assert_eq!(
        fs::read_to_string(dir.join("prereq-order.txt")).expect("missing prereq-order.txt"),
        "prereq\nmain\n"
    );
}

#[test]
fn failing_prerequisite_stops_before_main_workflow_and_reports_help() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-prerequisites-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("README.md").exists());
    assert_eq!(
        fs::read_to_string(dir.join("prereq-failure-order.txt"))
            .expect("missing prereq-failure-order.txt"),
        "prereq\n"
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Prerequisite failed: Docker daemon"));
    assert!(stderr.contains("Start Docker Desktop before running this example."));
}

#[test]
fn java_prerequisites_can_pass_before_main_workflow_runs() {
    let dir = prepare_workspace();
    let java_17_home = create_fake_java_home(&dir, "jdk-17", "17");
    let java_24_home = create_fake_java_home(&dir, "jdk-24", "24");
    write_runbook(
        &dir,
        "sw-runbook-run-prerequisites-java-success.json",
        "sw-runbook.json",
    );

    let output = run_in_dir_with_env(
        &["run"],
        &dir,
        &[
            ("JAVA_17_HOME", &java_17_home),
            ("JAVA_24_HOME", &java_24_home),
        ],
    );

    assert!(output.status.success());
    assert_eq!(
        fs::read_to_string(dir.join("prereq-java-order.txt")).expect("missing prereq-java-order"),
        "main\n"
    );
}

#[test]
fn command_indent_applies_to_shell_caption_and_output() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-indent.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("2. Build the application"));
    assert!(readme.contains("   ```shell\n   printf 'build ok\\n'\n   ```"));
    assert!(readme.contains("\n\n   Build output\n\n"));
    assert!(readme.contains("   ```\n   build ok\n   ```"));
}

#[test]
fn output_trailing_whitespace_is_trimmed_by_default() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-trim-default.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```\n  left\n\nright\n```"));
}

#[test]
fn output_trailing_whitespace_can_be_preserved() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-trim-disabled.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```\n  left  \n   \nright   \n```"));
}

#[test]
fn invalid_runbook_returns_validation_failure_without_output_file() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-invalid-prerequisite-help.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("README.md").exists());

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("Runbook is invalid"));
    assert!(stdout.contains(
        "Prerequisite check help must be a single string, not an array. Remove the surrounding [ ]."
    ));
    assert!(stdout.contains("Offending block:"));
    assert!(stdout.contains("\"name\": \"jq\""));
    assert!(stdout.contains("\"help\": ["));
}

#[test]
fn missing_input_file_returns_operational_error() {
    let dir = prepare_workspace();

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(1));
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Failed to read"));
}

#[test]
fn command_failure_returns_exit_code_two_without_output_file() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-failure.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("README.md").exists());
    assert_eq!(
        fs::read_to_string(dir.join("failure-sequence.txt"))
            .expect("missing side-effect from first command"),
        "before failure\n"
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Command failed assertion for entry:"));
    assert!(stderr.contains("\"commands\": ["));
    assert!(stderr.contains("\"false\""));
    assert!(stderr.contains("stdout:\n(empty)"));
    assert!(stderr.contains("stderr:\n(empty)"));
    assert!(stderr.contains("expected exit code 0, got 1"));
}

#[test]
fn command_failure_reports_captured_stdout_and_stderr() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-failure-with-output.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("README.md").exists());

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("stdout:\nfrom stdout\n"));
    assert!(stderr.contains("stderr:\nfrom stderr\n"));
    assert!(stderr.contains("expected exit code 0, got 1: from stderr"));
}

#[test]
fn asserted_exit_code_allows_non_zero_command_and_run_continues() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-assert-exit-success.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    assert_eq!(
        fs::read_to_string(dir.join("assert-sequence.txt")).expect("missing follow-up effect"),
        "after assert\n"
    );

    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Assertion passed"));
    assert!(readme.contains("```\nexpected output\n```"));
}

#[test]
fn asserted_exit_code_mismatch_fails_without_partial_output() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-assert-exit-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("README.md").exists());
    assert_eq!(
        fs::read_to_string(dir.join("assert-mismatch.txt")).expect("missing side effect"),
        "before mismatch\n"
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Command failed assertion for entry:"));
    assert!(stderr.contains("\"commands\": ["));
    assert!(stderr.contains("\"false\""));
    assert!(stderr.contains("stdout:\n(empty)"));
    assert!(stderr.contains("stderr:\n(empty)"));
    assert!(stderr.contains("expected exit code 0, got 1"));
}

#[test]
fn stdout_contains_assertion_allows_run_to_continue() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-stdout-contains-success.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Captured output"));
    assert!(readme.contains("```\nAlbert Attard\nHello there\n```"));
}

#[test]
fn multiple_stdout_contains_assertions_must_all_pass() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-stdout-contains-multiple.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("# Multiple stdout checks"));
}

#[test]
fn stdout_contains_assertion_failure_stops_the_run_without_partial_output() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-stdout-contains-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("README.md").exists());
    assert!(!dir.join("contains-failure.txt").exists());

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Command failed assertion for entry:"));
    assert!(stderr.contains("\"commands\": ["));
    assert!(stderr.contains("\"printf 'actual output\\\\n'\""));
    assert!(stderr.contains("stdout:\nactual output\n"));
    assert!(stderr.contains("stderr:\n(empty)"));
    assert!(stderr.contains("stdout did not contain `expected output`"));
}

#[test]
fn file_exists_assertion_allows_run_to_continue() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-assert-file-exists-success.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    assert!(dir.join("artifact.txt").exists());
}

#[test]
fn file_exists_assertion_failure_stops_the_run_without_partial_output() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-assert-file-exists-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("README.md").exists());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("file `./artifact.txt` did not exist"));
}

#[test]
fn file_sha256_assertion_allows_run_to_continue() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-assert-file-sha256-success.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    assert!(dir.join("artifact.txt").exists());
}

#[test]
fn file_sha256_assertion_failure_stops_the_run_without_partial_output() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-assert-file-sha256-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("README.md").exists());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("file `./artifact.txt` had sha256 `5b3513f580c8397212ff2c8f459c199efc0c90e4354a5f3533adf0a3fff3a530` instead of `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`"));
}

#[test]
fn command_with_timeout_completing_in_time_succeeds() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-timeout-success.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Timeout success output"));
    assert!(readme.contains("```\ncompleted quickly\n```"));
}

#[test]
fn timed_out_command_is_terminated_and_preserves_partial_output() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-timeout-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("timeout-after.txt").exists());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("# Timeout failure"));
    assert!(readme.contains("Timed out output"));
    assert!(readme.contains("```\nbefore timeout\n```"));

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Command timed out after 1 second"));
}

#[test]
fn cleanup_runs_in_reverse_order_after_successful_run() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-cleanup-success.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    assert_eq!(
        fs::read_to_string(dir.join("cleanup-order.txt")).expect("missing cleanup order file"),
        "A main\nB main\nB cleanup\nA cleanup\n"
    );
}

#[test]
fn cleanup_runs_after_command_failure() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-cleanup-on-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("README.md").exists());
    assert_eq!(
        fs::read_to_string(dir.join("cleanup-on-failure.txt"))
            .expect("missing cleanup-on-failure file"),
        "before failure\ncleanup after failure\n"
    );
}

#[test]
fn cleanup_runs_after_timeout() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-cleanup-on-timeout.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert_eq!(
        fs::read_to_string(dir.join("cleanup-on-timeout.txt"))
            .expect("missing cleanup-on-timeout file"),
        "before timeout\ncleanup after timeout\n"
    );
}

#[test]
fn cleanup_supports_multiline_control_structures() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-cleanup-multiline-control-structure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    assert_eq!(
        fs::read_to_string(dir.join("cleanup-multiline.txt"))
            .expect("missing cleanup multiline file"),
        "main\ncleanup context\n"
    );
}

#[test]
fn cleanup_failures_do_not_stop_remaining_cleanup_and_fail_the_run() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-cleanup-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```shell"));
    assert_eq!(
        fs::read_to_string(dir.join("cleanup-failure-order.txt"))
            .expect("missing cleanup failure order file"),
        "A main\nB main\nB cleanup\nA cleanup 1\nA cleanup 2\n"
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Cleanup failed"));
}

#[test]
fn command_without_cleanup_automatically_terminates_started_processes_after_success() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-auto-process-cleanup-success.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    assert_eq!(
        fs::read_to_string(dir.join("auto-cleanup-success-state.txt"))
            .expect("missing auto cleanup success state"),
        "dead\n"
    );
}

#[test]
fn command_without_cleanup_automatically_terminates_started_processes_after_failure() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-auto-process-cleanup-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    let pid = fs::read_to_string(dir.join("auto-cleanup-failure.pid"))
        .expect("missing auto cleanup failure pid")
        .trim()
        .to_string();
    let probe = std::process::Command::new("sh")
        .arg("-lc")
        .arg(format!("kill -0 \"{pid}\" 2>/dev/null"))
        .current_dir(&dir)
        .status()
        .expect("failed to probe auto cleanup failure pid");
    assert!(!probe.success());
}

#[test]
fn command_without_cleanup_automatically_terminates_started_processes_after_timeout() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-auto-process-cleanup-timeout.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    let pid = fs::read_to_string(dir.join("auto-cleanup-timeout.pid"))
        .expect("missing auto cleanup timeout pid")
        .trim()
        .to_string();
    let probe = std::process::Command::new("sh")
        .arg("-lc")
        .arg(format!("kill -0 \"{pid}\" 2>/dev/null"))
        .current_dir(&dir)
        .status()
        .expect("failed to probe auto cleanup timeout pid");
    assert!(!probe.success());
}

#[test]
fn automatic_cleanup_treats_missing_process_group_as_noop() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-auto-process-cleanup-missing-process-noop.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(!stderr.contains("No such process"));
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Command output"));
    assert!(readme.contains("done"));
}

#[test]
fn command_with_cleanup_uses_manual_cleanup_instead_of_automatic_process_cleanup() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-manual-cleanup-overrides-auto.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    assert_eq!(
        fs::read_to_string(dir.join("manual-cleanup-state.txt"))
            .expect("missing manual cleanup state"),
        "alive\n"
    );
    assert_eq!(
        fs::read_to_string(dir.join("manual-cleanup-log.txt")).expect("missing manual cleanup log"),
        "manual cleanup\n"
    );
    let pid = fs::read_to_string(dir.join("manual-cleanup.pid"))
        .expect("missing manual cleanup pid")
        .trim()
        .to_string();
    let probe = std::process::Command::new("sh")
        .arg("-lc")
        .arg(format!("kill -0 \"{pid}\" 2>/dev/null"))
        .current_dir(&dir)
        .status()
        .expect("failed to probe manual cleanup pid");
    assert!(!probe.success());
}

#[test]
fn json_output_content_type_uses_json_fenced_block() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-output-json.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```json\n{\"name\":\"Albert Attard\"}\n```"));
}

#[test]
fn output_without_content_type_uses_text_fenced_block() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-success.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```\nHello there\n```"));
}

#[test]
fn output_with_text_content_type_uses_unlabeled_fenced_block() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-output-text.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```\nplain text\n```"));
}

#[test]
fn output_rewrite_replace_rules_apply_in_order() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-replace.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```\nuser=demo-user path=/path/to/project\n```"));
}

#[test]
fn output_rewrite_replace_rules_can_interpolate_earlier_captures() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-replacement-capture.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```\naudio file> @{audio_name}: demo.mp3\n```"));
}

#[test]
fn output_rewrite_patterns_can_interpolate_earlier_captures() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-pattern-capture.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```\naudio file> @{audio_path_raw}: demo.mp3\n```"));
}

#[test]
fn rewrite_capture_as_generates_original_and_rewritten_variables() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-rewrite-generated-capture-pair.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    assert_eq!(
        fs::read_to_string(dir.join("original-name.txt")).expect("missing original-name.txt"),
        "audio_20260312_142351\n"
    );
    assert_eq!(
        fs::read_to_string(dir.join("rewritten-name.txt")).expect("missing rewritten-name.txt"),
        "audio_20770427_123456\n"
    );
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Original: `audio_20260312_142351`"));
    assert!(readme.contains("Rewritten: `audio_20770427_123456`"));
}

#[test]
fn rewrite_capture_as_failure_reports_command_context_and_streams() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-rewrite-capture-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("README.md").exists());

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Rewrite capture_as failed for entry:"));
    assert!(stderr.contains("\"capture_as\": \"continuous_recording_pid\""));
    assert!(stderr.contains("stdout:"));
    assert!(stderr.contains("12283 ./target/other-app.jar"));
    assert!(stderr.contains("stderr:\n(empty)"));
    assert!(stderr.contains(
        "Rewrite capture_as `continuous_recording_pid` matched 0 values; expected exactly one"
    ));
}

#[test]
fn output_rewrite_datetime_shift_preserves_relative_timing() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-datetime-shift.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("2077-04-27T12:34:56.789+01:00 INFO Starting"));
    assert!(readme.contains("2077-04-27T12:34:58.789+01:00 INFO Ready"));
}

#[test]
fn output_rewrite_datetime_shift_uses_default_base_when_omitted() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-datetime-shift-default-base.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("2077-04-27T12:34:56.789+01:00 INFO Starting"));
    assert!(readme.contains("2077-04-27T12:34:58.789+01:00 INFO Ready"));
}

#[test]
fn output_rewrite_datetime_shift_supports_rfc3339_without_fractional_seconds() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-datetime-shift-rfc3339-no-fraction.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("2077-04-27T12:34:56+01:00 INFO Starting"));
    assert!(readme.contains("2077-04-27T12:34:58+01:00 INFO Ready"));
}

#[test]
fn output_rewrite_datetime_shift_supports_rfc3339_nanosecond_precision() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-datetime-shift-rfc3339-nanos.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("2077-04-27T12:34:56.789000000+01:00 INFO Starting"));
    assert!(readme.contains("2077-04-27T12:34:58.789000000+01:00 INFO Ready"));
}

#[test]
fn output_rewrite_datetime_shift_supports_rfc1123() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-datetime-shift-rfc1123.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Tue, 27 Apr 2077 12:34:56 GMT INFO Starting"));
    assert!(readme.contains("Tue, 27 Apr 2077 12:34:58 GMT INFO Ready"));
}

#[test]
fn output_rewrite_datetime_shift_can_share_one_anchor_across_formats() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-datetime-shift-shared-anchor.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("2077-04-27T12:34:56.789+01:00 INFO Main"));
    assert!(readme.contains("Tue, 27 Apr 2077 12:34:58 GMT INFO Http"));
    assert!(readme.contains("audio_20770427_123459"));
}

#[test]
fn output_rewrite_datetime_shift_can_reuse_one_anchor_across_commands() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-valid-output-rewrite-datetime-shift-use-cross-command.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("2077-04-27T12:34:56.789+01:00 INFO Main"));
    assert!(readme.contains("Tue, 27 Apr 2077 12:34:58 GMT INFO Http"));
    assert!(readme.contains("audio_20770427_123459"));
}

#[test]
fn output_rewrite_datetime_shift_supports_time_only_custom_formats() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-datetime-shift-time-only.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Started at 12:34:56.789"));
    assert!(readme.contains("Finished at 12:34:58.289"));
}

#[test]
fn output_rewrite_datetime_shift_time_only_can_reuse_shared_anchor() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-datetime-shift-time-only-shared-anchor.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("2077-04-27T12:34:56.789+01:00 INFO Main"));
    assert!(readme.contains("Started at 12:34:58.289"));
    assert!(readme.contains("Finished at 12:34:59.789"));
}

#[test]
fn output_rewrite_datetime_shift_time_only_wraps_across_midnight() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-datetime-shift-time-only-wrap.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Start 23:59:58.000"));
    assert!(readme.contains("End 00:00:01.000"));
}

#[test]
fn command_capture_raw_stage_supports_later_command_interpolation_and_escape() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-capture-raw.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    assert_eq!(
        fs::read_to_string(dir.join("captured-raw.txt")).expect("missing captured-raw.txt"),
        "/tmp/sw-demo-raw/file.txt\n"
    );
    assert_eq!(
        fs::read_to_string(dir.join("captured-literal.txt")).expect("missing captured-literal.txt"),
        "@{generated_path}\n"
    );
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("printf '%s\\n' '/tmp/sw-demo-raw/file.txt' > captured-raw.txt"));
    assert!(readme.contains("printf '%s\\n' '@{generated_path}' > captured-literal.txt"));
}

#[test]
fn output_rewrite_keep_between_uses_default_exclusive_boundaries() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-keep-between-default.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Kept output"));
    assert!(readme.contains("```\n...\nUsing Java 25.0.2\n...\n```"));
    assert!(!readme.contains("```\n[INFO] before\nUsing Java 25.0.2\n[INFO] after\n```"));
}

#[test]
fn output_rewrite_keep_between_applies_explicit_offsets() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-keep-between-offsets.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains(
        "```\nbefore context\n[INFO] --- exec:3.6.3:exec (default-cli) @ demo ---\nUsing Java 25.0.2\nBuild successful\n[INFO] ------------------------------------------------------------------------\nafter context\n```"
    ));
}

#[test]
fn output_rewrite_keep_between_leaves_output_unchanged_when_boundary_is_missing() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-keep-between-missing.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```\n[INFO] before\nUsing Java 25.0.2\n[INFO] after\n```"));
}

#[test]
fn output_rewrite_keep_between_can_hide_trim_markers() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-keep-between-no-markers.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Kept output without markers"));
    assert!(readme.contains("```\nUsing Java 25.0.2\n```"));
    assert!(!readme.contains("```\n...\nUsing Java 25.0.2\n...\n```"));
}

#[test]
fn output_rewrite_keep_between_can_show_only_a_leading_trim_marker() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-keep-between-start-only-markers.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Kept output with leading trim marker"));
    assert!(readme.contains(
        "```\n...\n================================================================================\n=== Performance Results ===\n================================================================================\nUse Compact Object Headers:   false\nHeap Size:                    96M\nFull GC Count:                0\n================================================================================\n```"
    ));
    assert!(!readme.contains(
        "```\n...\n================================================================================\n=== Performance Results ===\n================================================================================\nUse Compact Object Headers:   false\nHeap Size:                    96M\nFull GC Count:                0\n================================================================================\n...\n```"
    ));
}

#[test]
fn output_rewrite_keep_between_can_show_only_a_trailing_trim_marker() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-keep-between-end-only.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Kept output with trailing trim marker"));
    assert!(readme.contains(
        "```\n================================================================================\n=== Performance Results ===\n================================================================================\nUse Compact Object Headers:   false\nHeap Size:                    96M\nFull GC Count:                0\n================================================================================\n...\n```"
    ));
    assert!(!readme.contains(
        "```\n...\n================================================================================\n=== Performance Results ===\n================================================================================\nUse Compact Object Headers:   false\nHeap Size:                    96M\nFull GC Count:                0\n================================================================================\n...\n```"
    ));
}

#[test]
fn output_rewrite_keep_between_can_keep_from_start_to_end_without_trim_markers() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-keep-between-start-to-end.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Kept output from start to end"));
    assert!(readme.contains(
        "```\n================================================================================\n=== Performance Results ===\n================================================================================\nUse Compact Object Headers:   false\nHeap Size:                    96M\nFull GC Count:                0\n================================================================================\n```"
    ));
    assert!(!readme.contains(
        "```\n[INFO] before\n================================================================================"
    ));
}

#[test]
fn command_capture_rewritten_stage_uses_rewritten_stdout() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-capture-rewritten.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    assert_eq!(
        fs::read_to_string(dir.join("captured-rewritten.txt"))
            .expect("missing captured-rewritten.txt"),
        "./target/audio/demo.mp3\n"
    );
}

#[test]
fn command_capture_fails_when_pattern_matches_multiple_values() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-capture-multiple-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("README.md").exists());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Command capture `token` matched 2 values"));
}

#[test]
fn markdown_interpolates_earlier_captured_values_and_preserves_escaped_literals() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-markdown-interpolation-earlier-capture.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("Captured file: `audio_20770427_123500.mp3`"));
    assert!(readme.contains("Literal example: `@{audio_file_1}`"));
}

#[test]
fn xml_output_content_type_uses_xml_fenced_block() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-output-xml.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```xml\n<name>Albert Attard</name>\n```"));
}

#[test]
fn display_file_java_uses_java_fenced_block() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-display-file.json", "sw-runbook.json");
    fs::write(
        dir.join("Example.java"),
        "public class Example {\n    public static void main(String[] args) {}\n}\n",
    )
    .expect("failed to write Example.java");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("# Display file"));
    assert!(readme.contains("```java\npublic class Example {"));
}

#[test]
fn display_file_java_transform_can_collapse_a_method_body() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-display-file-transform-java-default.json",
        "sw-runbook.json",
    );
    fs::write(
        dir.join("Example.java"),
        "public final class Example {\n    public void initialize(final int moduloDivisor) {\n        int remainder = moduloDivisor % 2;\n        System.out.println(remainder);\n    }\n}\n",
    )
    .expect("failed to write Example.java");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(
        readme.contains(
            "public void initialize(final int moduloDivisor) { /* Closed for brevity */ }"
        )
    );
    assert!(!readme.contains("System.out.println"));
}

#[test]
fn display_file_can_render_a_bounded_line_range() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-display-file-line-range.json",
        "sw-runbook.json",
    );
    fs::write(dir.join("Example.java"), "line 1\nline 2\nline 3\nline 4\n")
        .expect("failed to write Example.java");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```java\nline 2\nline 3\n```"));
    assert!(!readme.contains("line 1"));
    assert!(!readme.contains("line 4"));
}

#[test]
fn display_file_can_render_from_start_line_to_end_of_file() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-display-file-start-line.json",
        "sw-runbook.json",
    );
    fs::write(dir.join("Example.java"), "line 1\nline 2\nline 3\nline 4\n")
        .expect("failed to write Example.java");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```java\nline 2\nline 3\nline 4\n```"));
    assert!(!readme.contains("line 1"));
}

#[test]
fn display_file_indent_prefixes_the_whole_fenced_block() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-display-file-indent-positive.json",
        "sw-runbook.json",
    );
    fs::write(dir.join("Example.java"), "line 1\n\nline 3\n")
        .expect("failed to write Example.java");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("  ```java\n  line 1\n\n  line 3\n  ```"));
}

#[test]
fn display_file_negative_offset_can_remove_leading_spaces() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-display-file-indent-negative.json",
        "sw-runbook.json",
    );
    fs::write(
        dir.join("Example.java"),
        "class Example {\n        public void demo() {\n            if (ready) {\n                work();\n            }\n        }\n}\n",
    )
    .expect("failed to write Example.java");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains(
        "```java\npublic void demo() {\n    if (ready) {\n        work();\n    }\n}\n```"
    ));
}

#[test]
fn display_file_positive_offset_can_add_leading_spaces_inside_the_fence() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-display-file-offset-positive.json",
        "sw-runbook.json",
    );
    fs::write(dir.join("Example.java"), "line 1\n\nline 3\n")
        .expect("failed to write Example.java");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```java\n    line 1\n\n    line 3\n```"));
}

#[test]
fn display_file_unknown_extension_falls_back_to_text() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-display-file-unknown-extension.json",
        "sw-runbook.json",
    );
    fs::write(dir.join("notes.custom"), "some notes\n").expect("failed to write notes.custom");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("README.md")).expect("missing readme output");
    assert!(readme.contains("```text\nsome notes\n```"));
}

#[test]
fn display_file_missing_file_returns_operational_error() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-display-file-missing.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(1));
    assert!(!dir.join("README.md").exists());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Failed to read"));
    assert!(stderr.contains("missing.java"));
}

#[test]
fn display_file_start_line_beyond_end_of_file_returns_operational_error() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-display-file-start-line.json",
        "sw-runbook.json",
    );
    fs::write(dir.join("Example.java"), "line 1\n").expect("failed to write Example.java");

    let runbook_path = dir.join("sw-runbook.json");
    let contents = fs::read_to_string(&runbook_path).expect("failed to read runbook");
    fs::write(
        &runbook_path,
        contents.replace("\"start_line\": 2", "\"start_line\": 3"),
    )
    .expect("failed to rewrite runbook");

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(1));
    assert!(!dir.join("README.md").exists());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("DisplayFile start_line 3 is beyond the end"));
}

#[test]
fn display_file_transform_missing_method_returns_render_failure() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-display-file-transform-java-missing-method.json",
        "sw-runbook.json",
    );
    fs::write(
        dir.join("Example.java"),
        "public final class Example {\n    public void initialize() {\n        System.out.println(\"hello\");\n    }\n}\n",
    )
    .expect("failed to write Example.java");

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("README.md").exists());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("DisplayFile transform failed"));
    assert!(stderr.contains("missingMethod"));
}
