use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

static NEXT_ID: AtomicU64 = AtomicU64::new(0);

fn unique_temp_dir() -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("time went backwards")
        .as_nanos();
    let id = NEXT_ID.fetch_add(1, Ordering::Relaxed);
    std::env::temp_dir().join(format!("sw-test-{}-{nanos}-{id}", std::process::id()))
}

fn prepare_workspace() -> PathBuf {
    let dir = unique_temp_dir();
    fs::create_dir_all(&dir).expect("failed to create temp dir");
    dir
}

fn run_in_dir(args: &[&str], dir: &Path) -> std::process::Output {
    Command::new(env!("CARGO_BIN_EXE_sw"))
        .args(args)
        .current_dir(dir)
        .output()
        .expect("failed to execute sw")
}

fn write_runbook(dir: &Path, fixture_name: &str, target_name: &str) -> PathBuf {
    let source = Path::new("tests/fixtures").join(fixture_name);
    let target = dir.join(target_name);
    let contents = fs::read_to_string(source).expect("failed to read fixture");
    fs::write(&target, contents).expect("failed to write fixture");
    target
}

#[test]
fn no_args_defaults_to_run_and_writes_readme() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-success.json", "sw-runbook.json");

    let output = run_in_dir(&[], &dir);

    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("Rendered runbook to readme.md"));

    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.starts_with(
        "<!-- Generated by Sociable Weaver. Manual edits will be overwritten when regenerated. -->\n\n"
    ));
    assert!(readme.contains("# Runbook execution"));
    assert!(readme.contains("```shell"));
    assert!(readme.contains("```\nHello there\n```"));
    assert!(!readme.contains("```text\nfirst\n```"));
    assert_eq!(
        fs::read_to_string(dir.join("sequence.txt")).expect("missing command side effect"),
        "first\nsecond\n"
    );
}

#[test]
fn run_command_writes_requested_output_file() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-success.json", "example.json");

    let output = run_in_dir(
        &[
            "run",
            "--input-file",
            "example.json",
            "--output-format",
            "markdown",
            "--output-file",
            "custom.md",
        ],
        &dir,
    );

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("custom.md")).expect("missing custom output");
    assert!(readme.starts_with(
        "<!-- Generated by Sociable Weaver. Manual edits will be overwritten when regenerated. -->\n\n"
    ));
    assert!(readme.contains("Captured output"));
    assert!(readme.contains("```\nHello there\n```"));
    assert!(!readme.contains("```text\nfirst\n```"));
}

#[test]
fn generated_marker_appears_before_rendered_entries() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-success.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    let marker =
        "<!-- Generated by Sociable Weaver. Manual edits will be overwritten when regenerated. -->";
    assert!(readme.starts_with(marker));
    assert!(readme.contains(&format!("{marker}\n\n# Runbook execution")));
}

#[test]
fn multiline_command_lines_share_the_same_shell_context() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-multiline.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("NAME='Albert Attard'\necho ${NAME}"));
    assert!(readme.contains("Name output"));
    assert!(readme.contains("```\nAlbert Attard\n```"));
}

#[test]
fn command_indent_applies_to_shell_caption_and_output() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-indent.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("2. Build the application"));
    assert!(readme.contains("   ```shell\n   printf 'build ok\\n'\n   ```"));
    assert!(readme.contains("\n\n   Build output\n\n"));
    assert!(readme.contains("   ```\n   build ok\n   ```"));
}

#[test]
fn output_trailing_whitespace_is_trimmed_by_default() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-trim-default.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("```\n  left\n\nright\n```"));
}

#[test]
fn output_trailing_whitespace_can_be_preserved() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-trim-disabled.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("```\n  left  \n   \nright   \n```"));
}

#[test]
fn invalid_runbook_returns_validation_failure_without_output_file() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-missing-field.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("readme.md").exists());

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("Runbook is invalid"));
}

#[test]
fn missing_input_file_returns_operational_error() {
    let dir = prepare_workspace();

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(1));
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Failed to read"));
}

#[test]
fn command_failure_returns_exit_code_two_without_output_file() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-failure.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("readme.md").exists());
    assert_eq!(
        fs::read_to_string(dir.join("failure-sequence.txt"))
            .expect("missing side-effect from first command"),
        "before failure\n"
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("expected exit code 0, got 1"));
}

#[test]
fn asserted_exit_code_allows_non_zero_command_and_run_continues() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-assert-exit-success.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    assert_eq!(
        fs::read_to_string(dir.join("assert-sequence.txt")).expect("missing follow-up effect"),
        "after assert\n"
    );

    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("Assertion passed"));
    assert!(readme.contains("```\nexpected output\n```"));
}

#[test]
fn asserted_exit_code_mismatch_fails_without_partial_output() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-assert-exit-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("readme.md").exists());
    assert_eq!(
        fs::read_to_string(dir.join("assert-mismatch.txt")).expect("missing side effect"),
        "before mismatch\n"
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("expected exit code 0, got 1"));
}

#[test]
fn stdout_contains_assertion_allows_run_to_continue() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-stdout-contains-success.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("Captured output"));
    assert!(readme.contains("```\nAlbert Attard\nHello there\n```"));
}

#[test]
fn multiple_stdout_contains_assertions_must_all_pass() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-stdout-contains-multiple.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("# Multiple stdout checks"));
}

#[test]
fn stdout_contains_assertion_failure_stops_the_run_without_partial_output() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-stdout-contains-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("readme.md").exists());
    assert!(!dir.join("contains-failure.txt").exists());

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("stdout did not contain `expected output`"));
}

#[test]
fn command_with_timeout_completing_in_time_succeeds() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-timeout-success.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("Timeout success output"));
    assert!(readme.contains("```\ncompleted quickly\n```"));
}

#[test]
fn timed_out_command_is_terminated_and_preserves_partial_output() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-timeout-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("timeout-after.txt").exists());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("# Timeout failure"));
    assert!(readme.contains("Timed out output"));
    assert!(readme.contains("```\nbefore timeout\n```"));

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Command timed out after 1 second"));
}

#[test]
fn cleanup_runs_in_reverse_order_after_successful_run() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-cleanup-success.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    assert_eq!(
        fs::read_to_string(dir.join("cleanup-order.txt")).expect("missing cleanup order file"),
        "A main\nB main\nB cleanup\nA cleanup\n"
    );
}

#[test]
fn cleanup_runs_after_command_failure() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-cleanup-on-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert!(!dir.join("readme.md").exists());
    assert_eq!(
        fs::read_to_string(dir.join("cleanup-on-failure.txt"))
            .expect("missing cleanup-on-failure file"),
        "before failure\ncleanup after failure\n"
    );
}

#[test]
fn cleanup_runs_after_timeout() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-cleanup-on-timeout.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    assert_eq!(
        fs::read_to_string(dir.join("cleanup-on-timeout.txt"))
            .expect("missing cleanup-on-timeout file"),
        "before timeout\ncleanup after timeout\n"
    );
}

#[test]
fn cleanup_failures_do_not_stop_remaining_cleanup_and_fail_the_run() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-cleanup-failure.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(2));
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("```shell"));
    assert_eq!(
        fs::read_to_string(dir.join("cleanup-failure-order.txt"))
            .expect("missing cleanup failure order file"),
        "A main\nB main\nB cleanup\nA cleanup 1\nA cleanup 2\n"
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Cleanup failed"));
}

#[test]
fn json_output_content_type_uses_json_fenced_block() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-output-json.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("```json\n{\"name\":\"Albert Attard\"}\n```"));
}

#[test]
fn output_without_content_type_uses_text_fenced_block() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-success.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("```\nHello there\n```"));
}

#[test]
fn output_with_text_content_type_uses_unlabeled_fenced_block() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-output-text.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("```\nplain text\n```"));
}

#[test]
fn output_rewrite_replace_rules_apply_in_order() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-replace.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("```\nuser=demo-user path=/path/to/project\n```"));
}

#[test]
fn output_rewrite_datetime_shift_preserves_relative_timing() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-datetime-shift.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("2077-04-27T12:34:56.789+01:00 INFO Starting"));
    assert!(readme.contains("2077-04-27T12:34:58.789+01:00 INFO Ready"));
}

#[test]
fn output_rewrite_datetime_shift_uses_default_base_when_omitted() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-datetime-shift-default-base.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("2077-04-27T12:34:56.789+01:00 INFO Starting"));
    assert!(readme.contains("2077-04-27T12:34:58.789+01:00 INFO Ready"));
}

#[test]
fn output_rewrite_datetime_shift_supports_rfc1123() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-output-rewrite-datetime-shift-rfc1123.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("Tue, 27 Apr 2077 12:34:56 GMT INFO Starting"));
    assert!(readme.contains("Tue, 27 Apr 2077 12:34:58 GMT INFO Ready"));
}

#[test]
fn xml_output_content_type_uses_xml_fenced_block() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-output-xml.json", "sw-runbook.json");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("```xml\n<name>Albert Attard</name>\n```"));
}

#[test]
fn display_file_java_uses_java_fenced_block() {
    let dir = prepare_workspace();
    write_runbook(&dir, "sw-runbook-run-display-file.json", "sw-runbook.json");
    fs::write(
        dir.join("Example.java"),
        "public class Example {\n    public static void main(String[] args) {}\n}\n",
    )
    .expect("failed to write Example.java");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("# Display file"));
    assert!(readme.contains("```java\npublic class Example {"));
}

#[test]
fn display_file_unknown_extension_falls_back_to_text() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-display-file-unknown-extension.json",
        "sw-runbook.json",
    );
    fs::write(dir.join("notes.custom"), "some notes\n").expect("failed to write notes.custom");

    let output = run_in_dir(&["run"], &dir);

    assert!(output.status.success());
    let readme = fs::read_to_string(dir.join("readme.md")).expect("missing readme output");
    assert!(readme.contains("```text\nsome notes\n```"));
}

#[test]
fn display_file_missing_file_returns_operational_error() {
    let dir = prepare_workspace();
    write_runbook(
        &dir,
        "sw-runbook-run-display-file-missing.json",
        "sw-runbook.json",
    );

    let output = run_in_dir(&["run"], &dir);

    assert_eq!(output.status.code(), Some(1));
    assert!(!dir.join("readme.md").exists());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("Failed to read"));
    assert!(stderr.contains("missing.java"));
}
