use super::RenderError;
use super::execute::{
    cleanup_block, ensure_assertions, execute_command, run_cleanup_blocks, timeout_label,
};
use serde_json::Value;
use std::fs;
use std::path::Path;

const GENERATED_MARKER: &str =
    "<!-- Generated by Sociable Weaver. Manual edits will be overwritten when regenerated. -->";

pub(crate) fn render_markdown(runbook: &Value, runbook_path: &Path) -> Result<String, RenderError> {
    let entries = runbook
        .get("entries")
        .and_then(Value::as_array)
        .ok_or_else(|| {
            RenderError::Operational("Runbook is missing an entries array".to_string())
        })?;

    let mut sections = Vec::new();
    let mut cleanups: Vec<Vec<String>> = Vec::new();
    let mut failure: Option<RenderError> = None;

    for entry in entries {
        let entry_type = entry.get("type").and_then(Value::as_str).ok_or_else(|| {
            RenderError::Operational("Runbook entry is missing a type".to_string())
        })?;

        let rendered = match entry_type {
            "Heading" => render_heading(entry)?,
            "Markdown" => render_markdown_entry(entry)?,
            "DisplayFile" => render_display_file(entry, runbook_path)?,
            "Command" => {
                if let Some(cleanup) = cleanup_block(entry)? {
                    cleanups.push(cleanup);
                }

                match render_command(entry) {
                    Ok(section) => section,
                    Err(RenderError::Timeout {
                        message,
                        partial_markdown,
                    }) => {
                        sections.push(partial_markdown);
                        failure = Some(RenderError::Timeout {
                            message,
                            partial_markdown: String::new(),
                        });
                        break;
                    }
                    Err(err) => {
                        failure = Some(err);
                        break;
                    }
                }
            }
            other => {
                return Err(RenderError::Operational(format!(
                    "Unsupported entry type `{other}`"
                )));
            }
        };

        sections.push(rendered);
    }

    let mut output = GENERATED_MARKER.to_string();
    if !sections.is_empty() {
        output.push_str("\n\n");
        output.push_str(&sections.join("\n\n"));
    }
    if !output.ends_with('\n') {
        output.push('\n');
    }

    let cleanup_failures = run_cleanup_blocks(&cleanups);
    let cleanup_message = if cleanup_failures.is_empty() {
        None
    } else {
        Some(format!(
            "Cleanup failed:\n- {}",
            cleanup_failures.join("\n- ")
        ))
    };

    match failure {
        Some(RenderError::Timeout { message, .. }) => Err(RenderError::Timeout {
            message: combine_messages(&message, cleanup_message.as_deref()),
            partial_markdown: output,
        }),
        Some(RenderError::CommandFailed(message)) => Err(RenderError::CommandFailed(
            combine_messages(&message, cleanup_message.as_deref()),
        )),
        Some(RenderError::Operational(message)) => Err(RenderError::Operational(combine_messages(
            &message,
            cleanup_message.as_deref(),
        ))),
        Some(RenderError::CleanupFailed { .. }) => unreachable!(),
        None => match cleanup_message {
            Some(message) => Err(RenderError::CleanupFailed {
                message,
                markdown: output,
            }),
            None => Ok(output),
        },
    }
}

fn render_display_file(entry: &Value, runbook_path: &Path) -> Result<String, RenderError> {
    let relative_path = entry
        .get("path")
        .and_then(Value::as_str)
        .ok_or_else(|| RenderError::Operational("DisplayFile entry is missing path".to_string()))?;
    let base_dir = runbook_path.parent().unwrap_or_else(|| Path::new("."));
    let display_path = base_dir.join(relative_path);
    let contents = fs::read_to_string(&display_path).map_err(|err| {
        RenderError::Operational(format!("Failed to read {}: {err}", display_path.display()))
    })?;

    let mut section = format!("```{}\n", display_file_content_type(&display_path));
    section.push_str(&contents);
    if !contents.ends_with('\n') && !contents.is_empty() {
        section.push('\n');
    }
    section.push_str("```");
    Ok(section)
}

fn render_heading(entry: &Value) -> Result<String, RenderError> {
    let level = entry
        .get("level")
        .and_then(Value::as_str)
        .ok_or_else(|| RenderError::Operational("Heading entry is missing level".to_string()))?;
    let title = entry
        .get("title")
        .and_then(Value::as_str)
        .ok_or_else(|| RenderError::Operational("Heading entry is missing title".to_string()))?;

    let marker = match level {
        "H1" => "#",
        "H2" => "##",
        "H3" => "###",
        "H4" => "####",
        "H5" => "#####",
        "H6" => "######",
        other => {
            return Err(RenderError::Operational(format!(
                "Unsupported heading level `{other}`"
            )));
        }
    };

    Ok(format!("{marker} {title}"))
}

fn render_markdown_entry(entry: &Value) -> Result<String, RenderError> {
    let contents = entry
        .get("contents")
        .and_then(Value::as_array)
        .ok_or_else(|| {
            RenderError::Operational("Markdown entry is missing contents".to_string())
        })?;

    let mut lines = Vec::new();
    for item in contents {
        lines.push(
            item.as_str()
                .ok_or_else(|| {
                    RenderError::Operational(
                        "Markdown contents must contain only strings".to_string(),
                    )
                })?
                .to_string(),
        );
    }

    Ok(lines.join("\n"))
}

fn render_command(entry: &Value) -> Result<String, RenderError> {
    let commands = entry
        .get("commands")
        .and_then(Value::as_array)
        .ok_or_else(|| RenderError::Operational("Command entry is missing commands".to_string()))?;

    let mut command_lines = Vec::new();
    for item in commands {
        command_lines.push(
            item.as_str()
                .ok_or_else(|| {
                    RenderError::Operational("Command list must contain only strings".to_string())
                })?
                .to_string(),
        );
    }

    let command_text = command_lines.join("\n");
    let mut section = format!("```shell\n{command_text}\n```");
    let execution = execute_command(entry, &command_text)?;

    if execution.timed_out {
        append_output(entry, &execution.stdout, &mut section)?;
        return Err(RenderError::Timeout {
            message: format!("Command timed out after {}", timeout_label(entry)),
            partial_markdown: apply_indent(entry, section)?,
        });
    }

    ensure_assertions(entry, &execution)?;
    append_output(entry, &execution.stdout, &mut section)?;
    apply_indent(entry, section)
}

fn append_output(entry: &Value, stdout: &str, section: &mut String) -> Result<(), RenderError> {
    let Some(output) = entry.get("output") else {
        return Ok(());
    };

    if let Some(caption) = output.get("caption") {
        let caption_text = render_caption(caption)?;
        section.push_str("\n\n");
        section.push_str(&caption_text);
    }

    section.push_str("\n\n");
    section.push_str(&format!("```{}\n", output_content_type(output)?));
    section.push_str(stdout);
    if !stdout.ends_with('\n') && !stdout.is_empty() {
        section.push('\n');
    }
    section.push_str("```");
    Ok(())
}

fn render_caption(caption: &Value) -> Result<String, RenderError> {
    match caption {
        Value::String(text) => Ok(text.to_string()),
        Value::Array(items) => {
            let mut lines = Vec::new();
            for item in items {
                lines.push(
                    item.as_str()
                        .ok_or_else(|| {
                            RenderError::Operational(
                                "Command output caption must contain only strings".to_string(),
                            )
                        })?
                        .to_string(),
                );
            }
            Ok(lines.join("\n"))
        }
        _ => Err(RenderError::Operational(
            "Command output caption must be a string or array of strings".to_string(),
        )),
    }
}

fn output_content_type(output: &Value) -> Result<&'static str, RenderError> {
    match output.get("content_type").and_then(Value::as_str) {
        Some("text") | None => Ok("text"),
        Some("json") => Ok("json"),
        Some("xml") => Ok("xml"),
        Some(other) => Err(RenderError::Operational(format!(
            "Unsupported output content type `{other}`"
        ))),
    }
}

fn display_file_content_type(path: &Path) -> &'static str {
    match path.extension().and_then(|extension| extension.to_str()) {
        Some("java") => "java",
        _ => "text",
    }
}

fn apply_indent(entry: &Value, section: String) -> Result<String, RenderError> {
    let Some(indent) = entry.get("indent") else {
        return Ok(section);
    };

    let indent_width = match (indent.as_u64(), indent.as_i64()) {
        (Some(width), _) => usize::try_from(width)
            .map_err(|_| RenderError::Operational("Command indent is too large".to_string()))?,
        (None, Some(width)) if width >= 0 => usize::try_from(width)
            .map_err(|_| RenderError::Operational("Command indent is too large".to_string()))?,
        _ => {
            return Err(RenderError::Operational(
                "Command indent must be a non-negative integer".to_string(),
            ));
        }
    };

    if indent_width == 0 {
        return Ok(section);
    }

    let prefix = " ".repeat(indent_width);
    Ok(section
        .lines()
        .map(|line| format!("{prefix}{line}"))
        .collect::<Vec<_>>()
        .join("\n"))
}

fn combine_messages(primary: &str, secondary: Option<&str>) -> String {
    match secondary {
        Some(secondary) => format!("{primary}\n{secondary}"),
        None => primary.to_string(),
    }
}
