use super::RenderError;
use super::execute::{
    cleanup_block, ensure_assertions, execute_command, run_cleanup_blocks, timeout_label,
};
use chrono::{DateTime, Duration, FixedOffset, NaiveDateTime, NaiveTime, TimeZone};
use regex::Regex;
use serde_json::Value;
use std::collections::HashMap;
use std::fs;
use std::io::{self, IsTerminal, Write};
use std::path::Path;
use std::process::Command;
use std::sync::{
    Arc,
    atomic::{AtomicBool, Ordering},
};
use std::thread;
use std::time::{Duration as StdDuration, Instant};

const GENERATED_MARKER: &str =
    "<!-- Generated by Sociable Weaver. Manual edits will be overwritten when regenerated. -->";
const DEFAULT_DATETIME_SHIFT_BASE: &str = "2077-04-27T12:34:56.789+01:00";
const RFC3339_PATTERN: &str = r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}[+-]\d{2}:\d{2}";
const RFC1123_PATTERN: &str = r"[A-Z][a-z]{2}, \d{2} [A-Z][a-z]{2} \d{4} \d{2}:\d{2}:\d{2} GMT";
const CAPTURE_NAME_PATTERN: &str = r"^[A-Za-z_][A-Za-z0-9_]*$";
const CAPTURE_INTERPOLATION_PATTERN: &str =
    r"@@\{([A-Za-z_][A-Za-z0-9_]*)\}|@\{([A-Za-z_][A-Za-z0-9_]*)\}";

struct RenderState {
    datetime_anchors: HashMap<String, DatetimeShiftAnchor>,
    captured_values: HashMap<String, String>,
}

struct RewriteCapturePair {
    original_name: String,
    original_value: String,
    rewritten_name: String,
    rewritten_value: String,
}

struct RewriteResult {
    rendered: String,
    generated_captures: Vec<RewriteCapturePair>,
}

pub(crate) fn render_markdown(
    runbook: &Value,
    runbook_path: &Path,
    verbose: bool,
) -> Result<String, RenderError> {
    let entries = runbook
        .get("entries")
        .and_then(Value::as_array)
        .ok_or_else(|| {
            RenderError::Operational("Runbook is missing an entries array".to_string())
        })?;

    let mut sections = Vec::new();
    let mut cleanups: Vec<Vec<String>> = Vec::new();
    let mut failure: Option<RenderError> = None;
    let mut state = RenderState {
        datetime_anchors: HashMap::new(),
        captured_values: HashMap::new(),
    };
    let mut progress = ProgressReporter::new(entries.len(), verbose);

    run_prerequisite_checks(entries)?;

    for (index, entry) in entries.iter().enumerate() {
        let entry_type = entry.get("type").and_then(Value::as_str).ok_or_else(|| {
            RenderError::Operational("Runbook entry is missing a type".to_string())
        })?;
        let progress_line = progress.start_entry(index, entry, runbook_path);

        let rendered = match entry_type {
            "Heading" => render_heading(entry)?,
            "Markdown" => render_markdown_entry(entry, &state.captured_values)?,
            "DisplayFile" => render_display_file(entry, runbook_path)?,
            "Prerequisite" => render_prerequisite_entry(entry)?,
            "Command" => {
                if let Some(cleanup) = cleanup_block(entry)? {
                    cleanups.push(cleanup);
                }

                match render_command(entry, &mut state) {
                    Ok(section) => section,
                    Err(RenderError::Timeout {
                        message,
                        partial_markdown,
                    }) => {
                        progress.finish_entry(progress_line);
                        sections.push(partial_markdown);
                        failure = Some(RenderError::Timeout {
                            message,
                            partial_markdown: String::new(),
                        });
                        break;
                    }
                    Err(err) => {
                        progress.finish_entry(progress_line);
                        failure = Some(err);
                        break;
                    }
                }
            }
            other => {
                return Err(RenderError::Operational(format!(
                    "Unsupported entry type `{other}`"
                )));
            }
        };

        progress.finish_entry(progress_line);
        sections.push(rendered);
    }

    let mut output = GENERATED_MARKER.to_string();
    if !sections.is_empty() {
        output.push_str("\n\n");
        output.push_str(&sections.join("\n\n"));
    }
    if !output.ends_with('\n') {
        output.push('\n');
    }

    let cleanup_failures = run_cleanup_blocks(&cleanups);
    let cleanup_message = if cleanup_failures.is_empty() {
        None
    } else {
        Some(format!(
            "Cleanup failed:\n- {}",
            cleanup_failures.join("\n- ")
        ))
    };

    match failure {
        Some(RenderError::Timeout { message, .. }) => Err(RenderError::Timeout {
            message: combine_messages(&message, cleanup_message.as_deref()),
            partial_markdown: output,
        }),
        Some(RenderError::CommandFailed(message)) => Err(RenderError::CommandFailed(
            combine_messages(&message, cleanup_message.as_deref()),
        )),
        Some(RenderError::Operational(message)) => Err(RenderError::Operational(combine_messages(
            &message,
            cleanup_message.as_deref(),
        ))),
        Some(RenderError::CleanupFailed { .. }) => unreachable!(),
        None => match cleanup_message {
            Some(message) => Err(RenderError::CleanupFailed {
                message,
                markdown: output,
            }),
            None => Ok(output),
        },
    }
}

#[derive(Clone, Copy)]
enum ProgressMode {
    Off,
    Plain,
    Live,
}

struct ProgressReporter {
    total_entries: usize,
    mode: ProgressMode,
}

struct EntryProgress {
    line: String,
    started_at: Instant,
    timeout: Option<String>,
    stop_signal: Option<Arc<AtomicBool>>,
    thread: Option<thread::JoinHandle<()>>,
}

impl ProgressReporter {
    fn new(total_entries: usize, verbose: bool) -> Self {
        let mode = if !verbose {
            ProgressMode::Off
        } else if io::stderr().is_terminal() {
            ProgressMode::Live
        } else {
            ProgressMode::Plain
        };

        Self {
            total_entries,
            mode,
        }
    }

    fn start_entry(
        &mut self,
        index: usize,
        entry: &Value,
        runbook_path: &Path,
    ) -> Option<EntryProgress> {
        match self.mode {
            ProgressMode::Off => None,
            ProgressMode::Plain => Some(EntryProgress {
                line: format_progress_line(
                    index + 1,
                    self.total_entries,
                    entry_summary(entry, runbook_path),
                ),
                started_at: Instant::now(),
                timeout: verbose_timeout_label(entry),
                stop_signal: None,
                thread: None,
            }),
            ProgressMode::Live => {
                let line = format_progress_line(
                    index + 1,
                    self.total_entries,
                    entry_summary(entry, runbook_path),
                );
                let stop_signal = Arc::new(AtomicBool::new(false));
                let thread_stop_signal = Arc::clone(&stop_signal);
                let thread_line = line.clone();
                let thread_timeout = verbose_timeout_label(entry);
                let started_at = Instant::now();
                let thread_started_at = started_at;
                let thread = thread::spawn(move || {
                    while !thread_stop_signal.load(Ordering::Relaxed) {
                        let _ = write_live_progress_line(
                            &thread_line,
                            &format_elapsed_time(thread_started_at.elapsed()),
                            thread_timeout.as_deref(),
                        );
                        thread::sleep(StdDuration::from_millis(100));
                    }
                });

                Some(EntryProgress {
                    line,
                    started_at,
                    timeout: verbose_timeout_label(entry),
                    stop_signal: Some(stop_signal),
                    thread: Some(thread),
                })
            }
        }
    }

    fn finish_entry(&mut self, progress: Option<EntryProgress>) {
        let Some(progress) = progress else {
            return;
        };

        match self.mode {
            ProgressMode::Off => {}
            ProgressMode::Plain => {
                let _ = writeln!(
                    io::stderr(),
                    "{}",
                    progress_line_text(
                        &progress.line,
                        &format_elapsed_time(progress.started_at.elapsed()),
                        progress.timeout.as_deref(),
                    )
                );
            }
            ProgressMode::Live => {
                if let Some(stop_signal) = &progress.stop_signal {
                    stop_signal.store(true, Ordering::Relaxed);
                }
                if let Some(thread) = progress.thread {
                    let _ = thread.join();
                }
                let _ = write_live_progress_line(
                    &progress.line,
                    &format_elapsed_time(progress.started_at.elapsed()),
                    progress.timeout.as_deref(),
                );
                let _ = writeln!(io::stderr());
            }
        }
    }
}

fn write_live_progress_line(line: &str, elapsed: &str, timeout: Option<&str>) -> io::Result<()> {
    let mut stderr = io::stderr().lock();
    write!(
        &mut stderr,
        "\r\x1b[2K{}",
        progress_line_text(line, elapsed, timeout)
    )?;

    stderr.flush()
}

fn progress_line_text(line: &str, elapsed: &str, timeout: Option<&str>) -> String {
    match timeout {
        Some(timeout) => format!("{line} ({elapsed} / {timeout})"),
        None => format!("{line} ({elapsed})"),
    }
}

fn format_elapsed_time(duration: StdDuration) -> String {
    if duration.as_secs() < 60 {
        return format!("{:.1}s", duration.as_secs_f64());
    }

    let minutes = duration.as_secs() / 60;
    let seconds = duration.as_secs() % 60;
    format!("{minutes}m {seconds}s")
}

fn verbose_timeout_label(entry: &Value) -> Option<String> {
    let entry_type = entry.get("type").and_then(Value::as_str)?;
    if entry_type != "Command" {
        return None;
    }

    let timeout = timeout_label(entry);
    Some(compact_timeout_label(&timeout))
}

fn compact_timeout_label(timeout: &str) -> String {
    let parts: Vec<_> = timeout.split_whitespace().collect();
    if parts.len() != 2 {
        return timeout.to_string();
    }

    let value = parts[0];
    match parts[1].to_ascii_lowercase().as_str() {
        "second" | "seconds" | "sec" | "secs" | "s" => format!("{value}s"),
        "minute" | "minutes" | "min" | "mins" | "m" => format!("{value}m"),
        _ => timeout.to_string(),
    }
}

fn format_progress_line(current: usize, total: usize, summary: String) -> String {
    let width = total.to_string().len();
    format!("[{current:>width$}/{total}] {summary}")
}

fn entry_summary(entry: &Value, runbook_path: &Path) -> String {
    let entry_type = entry.get("type").and_then(Value::as_str).unwrap_or("Entry");
    let summary = match entry_type {
        "Heading" => entry
            .get("title")
            .and_then(Value::as_str)
            .unwrap_or("Heading")
            .to_string(),
        "Markdown" => first_non_empty_array_string(entry.get("contents"))
            .unwrap_or_else(|| "Markdown".to_string()),
        "Command" => first_non_empty_array_string(entry.get("commands"))
            .unwrap_or_else(|| "Command".to_string()),
        "DisplayFile" => display_file_summary(entry, runbook_path),
        "Prerequisite" => prerequisite_summary(entry),
        other => other.to_string(),
    };

    format!("{entry_type}: {}", truncate_progress_summary(&summary, 80))
}

fn first_non_empty_array_string(value: Option<&Value>) -> Option<String> {
    let items = value?.as_array()?;
    for item in items {
        let text = item.as_str()?.trim();
        if !text.is_empty() {
            return Some(text.to_string());
        }
    }
    None
}

fn display_file_summary(entry: &Value, runbook_path: &Path) -> String {
    let relative_path = entry
        .get("path")
        .and_then(Value::as_str)
        .unwrap_or("<missing path>");
    let base_dir = runbook_path.parent().unwrap_or_else(|| Path::new("."));
    let display_path = base_dir.join(relative_path);
    let start_line = entry.get("start_line").and_then(Value::as_u64);
    let line_count = entry.get("line_count").and_then(Value::as_u64);

    match (start_line, line_count) {
        (Some(start), Some(count)) => {
            format!(
                "{} (lines {start}-{})",
                display_path.display(),
                start + count.saturating_sub(1)
            )
        }
        (Some(start), None) => format!("{} (from line {start})", display_path.display()),
        (None, _) => display_path.display().to_string(),
    }
}

fn prerequisite_summary(entry: &Value) -> String {
    let checks = entry
        .get("checks")
        .and_then(Value::as_array)
        .map(|checks| checks.len())
        .unwrap_or(0);
    if checks == 1 {
        "Prerequisite checks (1 check)".to_string()
    } else {
        format!("Prerequisite checks ({checks} checks)")
    }
}

fn truncate_progress_summary(summary: &str, max_chars: usize) -> String {
    let truncated: String = summary.chars().take(max_chars).collect();
    if summary.chars().count() > max_chars {
        format!("{truncated}...")
    } else {
        summary.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::{
        compact_timeout_label, entry_summary, format_elapsed_time, format_progress_line,
        progress_line_text, truncate_progress_summary,
    };
    use serde_json::json;
    use std::path::Path;
    use std::time::Duration;

    #[test]
    fn progress_line_pads_entry_numbers_to_total_width() {
        assert_eq!(
            format_progress_line(1, 12, "Markdown: Example".to_string()),
            "[ 1/12] Markdown: Example"
        );
        assert_eq!(
            format_progress_line(12, 12, "Markdown: Example".to_string()),
            "[12/12] Markdown: Example"
        );
    }

    #[test]
    fn progress_line_text_can_include_timeout_window() {
        assert_eq!(
            progress_line_text("[ 2/12] Command: demo", "1.2s", Some("2m")),
            "[ 2/12] Command: demo (1.2s / 2m)"
        );
        assert_eq!(
            progress_line_text("[ 2/12] Command: demo", "1.2s", None),
            "[ 2/12] Command: demo (1.2s)"
        );
    }

    #[test]
    fn elapsed_time_uses_seconds_under_one_minute_and_minutes_afterward() {
        assert_eq!(format_elapsed_time(Duration::from_millis(12_400)), "12.4s");
        assert_eq!(format_elapsed_time(Duration::from_secs(68)), "1m 8s");
    }

    #[test]
    fn compact_timeout_label_uses_short_units() {
        assert_eq!(compact_timeout_label("2 minutes"), "2m");
        assert_eq!(compact_timeout_label("30 seconds"), "30s");
    }

    #[test]
    fn entry_summary_uses_first_non_empty_line_for_markdown_and_command() {
        let markdown = json!({
            "type": "Markdown",
            "contents": ["", "1. Start the application", "More details"]
        });
        let command = json!({
            "type": "Command",
            "commands": ["", "java -jar './target/app.jar'", "echo done"]
        });

        assert_eq!(
            entry_summary(&markdown, Path::new("sw-runbook.json")),
            "Markdown: 1. Start the application"
        );
        assert_eq!(
            entry_summary(&command, Path::new("sw-runbook.json")),
            "Command: java -jar './target/app.jar'"
        );
    }

    #[test]
    fn display_file_summary_includes_line_range() {
        let display_file = json!({
            "type": "DisplayFile",
            "path": "./src/main.java",
            "start_line": 10,
            "line_count": 3
        });

        let summary = entry_summary(&display_file, Path::new("/tmp/sw-runbook.json"));
        assert!(summary.contains("DisplayFile: /tmp/./src/main.java (lines 10-12)"));
    }

    #[test]
    fn progress_summary_is_truncated_to_one_line() {
        let long_text = "a".repeat(100);
        let truncated = truncate_progress_summary(&long_text, 10);
        assert_eq!(truncated, "aaaaaaaaaa...");
    }
}

fn render_display_file(entry: &Value, runbook_path: &Path) -> Result<String, RenderError> {
    let relative_path = entry
        .get("path")
        .and_then(Value::as_str)
        .ok_or_else(|| RenderError::Operational("DisplayFile entry is missing path".to_string()))?;
    let base_dir = runbook_path.parent().unwrap_or_else(|| Path::new("."));
    let display_path = base_dir.join(relative_path);
    let contents = fs::read_to_string(&display_path).map_err(|err| {
        RenderError::Operational(format!("Failed to read {}: {err}", display_path.display()))
    })?;
    let start_line = entry
        .get("start_line")
        .and_then(Value::as_u64)
        .map(|value| value as usize)
        .unwrap_or(1);
    let line_count = entry
        .get("line_count")
        .and_then(Value::as_u64)
        .map(|value| value as usize);
    let contents = slice_display_file_contents(&contents, start_line, line_count, &display_path)?;
    let contents = apply_display_file_indent(entry, contents)?;

    let mut section = format!("```{}\n", display_file_content_type(&display_path));
    section.push_str(&contents);
    if !contents.ends_with('\n') && !contents.is_empty() {
        section.push('\n');
    }
    section.push_str("```");
    Ok(section)
}

fn apply_display_file_indent(entry: &Value, contents: String) -> Result<String, RenderError> {
    let Some(indent) = entry.get("indent") else {
        return Ok(contents);
    };

    let indent_width = match (indent.as_i64(), indent.as_u64()) {
        (Some(width), _) => width,
        (None, Some(width)) => i64::try_from(width)
            .map_err(|_| RenderError::Operational("DisplayFile indent is too large".to_string()))?,
        _ => {
            return Err(RenderError::Operational(
                "DisplayFile indent must be an integer".to_string(),
            ));
        }
    };

    if indent_width == 0 || contents.is_empty() {
        return Ok(contents);
    }

    let ends_with_newline = contents.ends_with('\n');
    let mut adjusted = contents
        .lines()
        .map(|line| apply_display_file_indent_to_line(line, indent_width))
        .collect::<Vec<_>>()
        .join("\n");

    if ends_with_newline {
        adjusted.push('\n');
    }

    Ok(adjusted)
}

fn apply_display_file_indent_to_line(line: &str, indent_width: i64) -> String {
    if line.is_empty() {
        return String::new();
    }

    if indent_width > 0 {
        return format!("{}{}", " ".repeat(indent_width as usize), line);
    }

    let spaces_to_remove = indent_width.unsigned_abs() as usize;
    let removable = line
        .as_bytes()
        .iter()
        .take_while(|byte| **byte == b' ')
        .take(spaces_to_remove)
        .count();

    line[removable..].to_string()
}

fn slice_display_file_contents(
    contents: &str,
    start_line: usize,
    line_count: Option<usize>,
    display_path: &Path,
) -> Result<String, RenderError> {
    let lines: Vec<&str> = contents.lines().collect();
    let start_index = start_line.saturating_sub(1);

    if start_index >= lines.len() && !lines.is_empty() {
        return Err(RenderError::Operational(format!(
            "DisplayFile start_line {} is beyond the end of {}",
            start_line,
            display_path.display()
        )));
    }

    let end_index = match line_count {
        Some(count) => start_index.saturating_add(count).min(lines.len()),
        None => lines.len(),
    };

    let mut sliced = lines[start_index..end_index].join("\n");
    if !sliced.is_empty() && contents.ends_with('\n') && end_index == lines.len() {
        sliced.push('\n');
    }

    Ok(sliced)
}

fn render_heading(entry: &Value) -> Result<String, RenderError> {
    let level = entry
        .get("level")
        .and_then(Value::as_str)
        .ok_or_else(|| RenderError::Operational("Heading entry is missing level".to_string()))?;
    let title = entry
        .get("title")
        .and_then(Value::as_str)
        .ok_or_else(|| RenderError::Operational("Heading entry is missing title".to_string()))?;

    let marker = match level {
        "H1" => "#",
        "H2" => "##",
        "H3" => "###",
        "H4" => "####",
        "H5" => "#####",
        "H6" => "######",
        other => {
            return Err(RenderError::Operational(format!(
                "Unsupported heading level `{other}`"
            )));
        }
    };

    Ok(format!("{marker} {title}"))
}

fn render_markdown_entry(
    entry: &Value,
    captured_values: &HashMap<String, String>,
) -> Result<String, RenderError> {
    let contents = entry
        .get("contents")
        .and_then(Value::as_array)
        .ok_or_else(|| {
            RenderError::Operational("Markdown entry is missing contents".to_string())
        })?;

    let mut lines = Vec::new();
    for item in contents {
        lines.push(
            item.as_str()
                .ok_or_else(|| {
                    RenderError::Operational(
                        "Markdown contents must contain only strings".to_string(),
                    )
                })?
                .to_string(),
        );
    }

    interpolate_command_lines(&lines, captured_values).map(|lines| lines.join("\n"))
}

fn render_command(entry: &Value, state: &mut RenderState) -> Result<String, RenderError> {
    let commands = entry
        .get("commands")
        .and_then(Value::as_array)
        .ok_or_else(|| RenderError::Operational("Command entry is missing commands".to_string()))?;

    let mut command_lines = Vec::new();
    for item in commands {
        command_lines.push(
            item.as_str()
                .ok_or_else(|| {
                    RenderError::Operational("Command list must contain only strings".to_string())
                })?
                .to_string(),
        );
    }

    let resolved_command_lines = interpolate_command_lines(&command_lines, &state.captured_values)?;
    let command_text = resolved_command_lines.join("\n");
    let mut section = format!("```shell\n{command_text}\n```");
    let execution = execute_command(entry, &command_text)?;
    let rewrite_result = rewritten_stdout_for_capture(entry, &execution.stdout, state)?;
    let rewritten_stdout = rewrite_result.rendered;

    if execution.timed_out {
        append_output(entry, &rewritten_stdout, &mut section)?;
        return Err(RenderError::Timeout {
            message: format!("Command timed out after {}", timeout_label(entry)),
            partial_markdown: apply_indent(entry, section)?,
        });
    }

    ensure_assertions(entry, &execution)?;
    extract_captured_values(
        entry,
        &execution.stdout,
        &rewritten_stdout,
        &mut state.captured_values,
    )?;
    store_generated_rewrite_captures(
        &rewrite_result.generated_captures,
        &mut state.captured_values,
    );
    append_output(entry, &rewritten_stdout, &mut section)?;
    apply_indent(entry, section)
}

fn append_output(entry: &Value, stdout: &str, section: &mut String) -> Result<(), RenderError> {
    let Some(output) = entry.get("output") else {
        return Ok(());
    };

    if let Some(caption) = output.get("caption") {
        let caption_text = render_caption(caption)?;
        section.push_str("\n\n");
        section.push_str(&caption_text);
    }

    section.push_str("\n\n");
    section.push_str(output_fence_open(output)?);
    section.push_str(stdout);
    if !stdout.ends_with('\n') && !stdout.is_empty() {
        section.push('\n');
    }
    section.push_str("```");
    Ok(())
}

fn render_caption(caption: &Value) -> Result<String, RenderError> {
    match caption {
        Value::String(text) => Ok(text.to_string()),
        Value::Array(items) => {
            let mut lines = Vec::new();
            for item in items {
                lines.push(
                    item.as_str()
                        .ok_or_else(|| {
                            RenderError::Operational(
                                "Command output caption must contain only strings".to_string(),
                            )
                        })?
                        .to_string(),
                );
            }
            Ok(lines.join("\n"))
        }
        _ => Err(RenderError::Operational(
            "Command output caption must be a string or array of strings".to_string(),
        )),
    }
}

fn render_prerequisite_entry(entry: &Value) -> Result<String, RenderError> {
    let checks = entry
        .get("checks")
        .and_then(Value::as_array)
        .ok_or_else(|| {
            RenderError::Operational("Prerequisite entry is missing checks".to_string())
        })?;

    let mut sections = Vec::new();
    for check in checks {
        let contents = check
            .get("contents")
            .and_then(Value::as_array)
            .ok_or_else(|| {
                RenderError::Operational("Prerequisite contents must be an array".to_string())
            })?;
        let mut lines = Vec::new();
        for item in contents {
            lines.push(
                item.as_str()
                    .ok_or_else(|| {
                        RenderError::Operational(
                            "Prerequisite contents must contain only strings".to_string(),
                        )
                    })?
                    .to_string(),
            );
        }
        sections.push(lines.join("\n"));
    }

    Ok(sections.join("\n\n"))
}

pub(crate) fn check_prerequisites(runbook: &Value) -> Result<(), RenderError> {
    let entries = runbook
        .get("entries")
        .and_then(Value::as_array)
        .ok_or_else(|| {
            RenderError::Operational("Runbook is missing an entries array".to_string())
        })?;
    run_prerequisite_checks(entries)
}

fn run_prerequisite_checks(entries: &[Value]) -> Result<(), RenderError> {
    for entry in entries {
        let Some("Prerequisite") = entry.get("type").and_then(Value::as_str) else {
            continue;
        };

        let checks = entry
            .get("checks")
            .and_then(Value::as_array)
            .ok_or_else(|| {
                RenderError::Operational("Prerequisite entry is missing checks".to_string())
            })?;

        for check in checks {
            run_prerequisite_check(check)?;
        }
    }

    Ok(())
}

fn run_prerequisite_check(check: &Value) -> Result<(), RenderError> {
    let name = check.get("name").and_then(Value::as_str).ok_or_else(|| {
        RenderError::Operational("Prerequisite name must be a string".to_string())
    })?;
    let kind = check.get("kind").and_then(Value::as_str).ok_or_else(|| {
        RenderError::Operational("Prerequisite kind must be a string".to_string())
    })?;

    match kind {
        "command" => run_command_prerequisite_check(check, name),
        "java" => run_java_prerequisite_check(check, name),
        other => Err(RenderError::Operational(format!(
            "Unsupported prerequisite kind `{other}`"
        ))),
    }
}

fn run_command_prerequisite_check(check: &Value, name: &str) -> Result<(), RenderError> {
    let commands = check
        .get("commands")
        .and_then(Value::as_array)
        .ok_or_else(|| {
            RenderError::Operational("Prerequisite commands must be an array".to_string())
        })?;

    let mut lines = Vec::new();
    for item in commands {
        lines.push(
            item.as_str()
                .ok_or_else(|| {
                    RenderError::Operational(
                        "Prerequisite commands must contain only strings".to_string(),
                    )
                })?
                .to_string(),
        );
    }

    let script = lines.join("\n");
    let execution = execute_command(check, &script)?;
    if execution.timed_out {
        return Err(prerequisite_failure(
            name,
            check.get("help").and_then(Value::as_str),
            &format!("timed out after {}", timeout_label(check)),
        ));
    }

    ensure_assertions(check, &execution).map_err(|err| match err {
        RenderError::CommandFailed(message) => {
            prerequisite_failure(name, check.get("help").and_then(Value::as_str), &message)
        }
        other => other,
    })?;

    Ok(())
}

fn run_java_prerequisite_check(check: &Value, name: &str) -> Result<(), RenderError> {
    let version = check
        .get("version")
        .and_then(Value::as_str)
        .ok_or_else(|| {
            RenderError::Operational("Prerequisite Java version must be a string".to_string())
        })?;
    let requirement = parse_java_version_requirement(version).ok_or_else(|| {
        RenderError::Operational("Prerequisite Java version must be like `17` or `24+`".to_string())
    })?;
    let executable = resolve_prerequisite_java_executable(check).map_err(|detail| {
        prerequisite_failure(name, check.get("help").and_then(Value::as_str), &detail)
    })?;

    let output = Command::new(&executable)
        .arg("-version")
        .output()
        .map_err(|err| {
            prerequisite_failure(
                name,
                check.get("help").and_then(Value::as_str),
                &format!("failed to execute `{}`: {err}", executable.display()),
            )
        })?;

    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    let combined = format!("{stdout}\n{stderr}");
    let detected = detect_java_major_version(&combined).ok_or_else(|| {
        prerequisite_failure(
            name,
            check.get("help").and_then(Value::as_str),
            &format!(
                "could not determine Java version from `{}`",
                executable.display()
            ),
        )
    })?;

    if requirement.matches(detected) {
        return Ok(());
    }

    Err(prerequisite_failure(
        name,
        check.get("help").and_then(Value::as_str),
        &format!(
            "expected Java version `{}`, found `{detected}`",
            requirement.display()
        ),
    ))
}

fn resolve_prerequisite_java_executable(check: &Value) -> Result<std::path::PathBuf, String> {
    if let Some(java_home) = check.get("java_home").and_then(Value::as_str) {
        return prerequisite_java_home_executable(java_home);
    }

    if let Some(java_home_env) = check.get("java_home_env").and_then(Value::as_str) {
        let value = std::env::var(java_home_env)
            .map_err(|_| format!("environment variable `{java_home_env}` is not set"))?;
        return prerequisite_java_home_executable(&value);
    }

    Ok(std::path::PathBuf::from("java"))
}

fn prerequisite_java_home_executable(java_home: &str) -> Result<std::path::PathBuf, String> {
    let executable = Path::new(java_home).join("bin").join("java");
    if executable.is_file() {
        Ok(executable)
    } else {
        Err(format!(
            "Java home `{java_home}` does not contain `bin/java`"
        ))
    }
}

struct JavaVersionRequirement {
    major: u32,
    minimum: bool,
}

impl JavaVersionRequirement {
    fn matches(&self, actual: u32) -> bool {
        if self.minimum {
            actual >= self.major
        } else {
            actual == self.major
        }
    }

    fn display(&self) -> String {
        if self.minimum {
            format!("{}+", self.major)
        } else {
            self.major.to_string()
        }
    }
}

fn parse_java_version_requirement(value: &str) -> Option<JavaVersionRequirement> {
    if let Some(prefix) = value.strip_suffix('+') {
        let major = prefix.parse().ok()?;
        return Some(JavaVersionRequirement {
            major,
            minimum: true,
        });
    }

    let major = value.parse().ok()?;
    Some(JavaVersionRequirement {
        major,
        minimum: false,
    })
}

fn detect_java_major_version(output: &str) -> Option<u32> {
    let quoted =
        Regex::new(r#"version "([^"]+)""#).expect("valid java quoted version detection regex");
    if let Some(captures) = quoted.captures(output) {
        return parse_java_major_from_version_string(captures.get(1)?.as_str());
    }

    let bare = Regex::new(r#"(?m)^(?:openjdk|java)\s+([0-9][0-9A-Za-z._+-]*)"#)
        .expect("valid java bare version detection regex");
    if let Some(captures) = bare.captures(output) {
        return parse_java_major_from_version_string(captures.get(1)?.as_str());
    }

    None
}

fn parse_java_major_from_version_string(value: &str) -> Option<u32> {
    let normalized = value.strip_prefix("1.").unwrap_or(value);
    let digits: String = normalized
        .chars()
        .take_while(|character| character.is_ascii_digit())
        .collect();
    if digits.is_empty() {
        None
    } else {
        digits.parse().ok()
    }
}

fn prerequisite_failure(name: &str, help: Option<&str>, detail: &str) -> RenderError {
    let mut message = format!("Prerequisite failed: {name}: {detail}");
    if let Some(help) = help {
        message.push('\n');
        message.push_str(help);
    }
    RenderError::CommandFailed(message)
}

fn output_fence_open(output: &Value) -> Result<&'static str, RenderError> {
    match output.get("content_type").and_then(Value::as_str) {
        Some("text") | None => Ok("```\n"),
        Some("json") => Ok("```json\n"),
        Some("xml") => Ok("```xml\n"),
        Some(other) => Err(RenderError::Operational(format!(
            "Unsupported output content type `{other}`"
        ))),
    }
}

fn normalize_rendered_output(
    output: &Value,
    stdout: &str,
    datetime_anchors: &mut HashMap<String, DatetimeShiftAnchor>,
    captured_values: &HashMap<String, String>,
) -> Result<RewriteResult, RenderError> {
    let rewrite_result = apply_rewrite_rules(output, stdout, datetime_anchors, captured_values)?;
    let rewritten = rewrite_result.rendered;

    if !trim_trailing_whitespace(output)? {
        return Ok(RewriteResult {
            rendered: rewritten,
            generated_captures: rewrite_result.generated_captures,
        });
    }

    Ok(RewriteResult {
        rendered: rewritten
            .split_inclusive('\n')
            .map(trim_segment_trailing_whitespace)
            .collect(),
        generated_captures: rewrite_result.generated_captures,
    })
}

fn rewritten_stdout_for_capture(
    entry: &Value,
    stdout: &str,
    state: &mut RenderState,
) -> Result<RewriteResult, RenderError> {
    let Some(output) = entry.get("output") else {
        return Ok(RewriteResult {
            rendered: stdout.to_string(),
            generated_captures: Vec::new(),
        });
    };

    normalize_rendered_output(
        output,
        stdout,
        &mut state.datetime_anchors,
        &state.captured_values,
    )
}

fn apply_rewrite_rules(
    output: &Value,
    stdout: &str,
    datetime_anchors: &mut HashMap<String, DatetimeShiftAnchor>,
    captured_values: &HashMap<String, String>,
) -> Result<RewriteResult, RenderError> {
    let Some(rules) = output.get("rewrite") else {
        return Ok(RewriteResult {
            rendered: stdout.to_string(),
            generated_captures: Vec::new(),
        });
    };
    let rules = rules.as_array().ok_or_else(|| {
        RenderError::Operational("Command output rewrite must be an array".to_string())
    })?;
    let mut rendered = stdout.to_string();
    let mut generated_captures = Vec::new();
    for rule in rules {
        let result = apply_rewrite_rule(rule, &rendered, datetime_anchors, captured_values)?;
        rendered = result.rendered;
        if let Some(capture) = result.generated_capture {
            generated_captures.push(capture);
        }
    }
    Ok(RewriteResult {
        rendered,
        generated_captures,
    })
}

fn store_generated_rewrite_captures(
    generated_captures: &[RewriteCapturePair],
    captured_values: &mut HashMap<String, String>,
) {
    for capture in generated_captures {
        captured_values.insert(
            capture.original_name.clone(),
            capture.original_value.clone(),
        );
        captured_values.insert(
            capture.rewritten_name.clone(),
            capture.rewritten_value.clone(),
        );
    }
}

fn extract_captured_values(
    entry: &Value,
    raw_stdout: &str,
    rewritten_stdout: &str,
    captured_values: &mut HashMap<String, String>,
) -> Result<(), RenderError> {
    let Some(capture) = entry.get("capture") else {
        return Ok(());
    };
    let captures = capture
        .as_array()
        .ok_or_else(|| RenderError::Operational("Command capture must be an array".to_string()))?;

    let name_pattern = Regex::new(CAPTURE_NAME_PATTERN).expect("valid capture name regex");

    for rule in captures {
        let name = rule.get("name").and_then(Value::as_str).ok_or_else(|| {
            RenderError::Operational("Command capture name must be a string".to_string())
        })?;
        if !name_pattern.is_match(name) {
            return Err(RenderError::Operational(format!(
                "Command capture name `{name}` is invalid"
            )));
        }

        let source = rule.get("source").and_then(Value::as_str).ok_or_else(|| {
            RenderError::Operational("Command capture source must be a string".to_string())
        })?;
        if source != "stdout" {
            return Err(RenderError::Operational(format!(
                "Unsupported command capture source `{source}`"
            )));
        }

        let stage = rule.get("stage").and_then(Value::as_str).ok_or_else(|| {
            RenderError::Operational("Command capture stage must be a string".to_string())
        })?;
        let candidate = match stage {
            "raw" => raw_stdout,
            "rewritten" => rewritten_stdout,
            other => {
                return Err(RenderError::Operational(format!(
                    "Unsupported command capture stage `{other}`"
                )));
            }
        };

        let pattern = rule.get("pattern").and_then(Value::as_str).ok_or_else(|| {
            RenderError::Operational("Command capture pattern must be a string".to_string())
        })?;
        let regex = Regex::new(pattern).map_err(|err| {
            RenderError::Operational(format!(
                "Invalid command capture pattern `{pattern}`: {err}"
            ))
        })?;

        let matches: Vec<String> = regex
            .captures_iter(candidate)
            .map(|captures| {
                captures
                    .get(1)
                    .or_else(|| captures.get(0))
                    .map(|value| value.as_str().to_string())
                    .unwrap_or_default()
            })
            .collect();

        match matches.len() {
            1 => {
                captured_values.insert(name.to_string(), matches[0].clone());
            }
            0 => {
                return Err(RenderError::CommandFailed(format!(
                    "Command capture `{name}` matched no value"
                )));
            }
            count => {
                return Err(RenderError::CommandFailed(format!(
                    "Command capture `{name}` matched {count} values; expected exactly one"
                )));
            }
        }
    }

    Ok(())
}

fn interpolate_command_lines(
    command_lines: &[String],
    captured_values: &HashMap<String, String>,
) -> Result<Vec<String>, RenderError> {
    command_lines
        .iter()
        .map(|line| interpolate_captured_variables(line, captured_values))
        .collect()
}

fn interpolate_captured_variables(
    input: &str,
    captured_values: &HashMap<String, String>,
) -> Result<String, RenderError> {
    interpolate_captured_variables_with_context(input, captured_values, "Command")
}

fn interpolate_captured_variables_with_context(
    input: &str,
    captured_values: &HashMap<String, String>,
    context: &str,
) -> Result<String, RenderError> {
    let regex =
        Regex::new(CAPTURE_INTERPOLATION_PATTERN).expect("valid capture interpolation regex");
    let mut output = String::with_capacity(input.len());
    let mut last_end = 0;

    for captures in regex.captures_iter(input) {
        let matched = captures.get(0).expect("full regex match");
        output.push_str(&input[last_end..matched.start()]);

        if let Some(escaped_name) = captures.get(1) {
            output.push_str(&format!("@{{{}}}", escaped_name.as_str()));
        } else if let Some(name) = captures.get(2) {
            let value = captured_values.get(name.as_str()).ok_or_else(|| {
                RenderError::CommandFailed(format!(
                    "{context} references unknown captured variable `@{{{}}}`",
                    name.as_str(),
                ))
            })?;
            output.push_str(value);
        }

        last_end = matched.end();
    }

    output.push_str(&input[last_end..]);
    Ok(output)
}

fn apply_rewrite_rule(
    rule: &Value,
    rendered: &str,
    datetime_anchors: &mut HashMap<String, DatetimeShiftAnchor>,
    captured_values: &HashMap<String, String>,
) -> Result<RewriteRuleResult, RenderError> {
    let rule_type = rule.get("type").and_then(Value::as_str).ok_or_else(|| {
        RenderError::Operational("Command output rewrite type must be a string".to_string())
    })?;

    match rule_type {
        "replace" => apply_replace_rule(rule, rendered, captured_values),
        "keep_between" => apply_keep_between_rule(rule, rendered),
        "datetime_shift" => apply_datetime_shift_rule(rule, rendered, datetime_anchors),
        other => Err(RenderError::Operational(format!(
            "Unsupported output rewrite type `{other}`"
        ))),
    }
}

struct RewriteRuleResult {
    rendered: String,
    generated_capture: Option<RewriteCapturePair>,
}

fn apply_replace_rule(
    rule: &Value,
    rendered: &str,
    captured_values: &HashMap<String, String>,
) -> Result<RewriteRuleResult, RenderError> {
    let pattern = rule.get("pattern").and_then(Value::as_str).ok_or_else(|| {
        RenderError::Operational("Command output rewrite pattern must be a string".to_string())
    })?;
    let pattern = interpolate_captured_variables_with_context(
        pattern,
        captured_values,
        "Command output rewrite pattern",
    )?;
    let replacement = rule
        .get("replacement")
        .and_then(Value::as_str)
        .ok_or_else(|| {
            RenderError::Operational(
                "Command output rewrite replacement must be a string".to_string(),
            )
        })?;
    let replacement = interpolate_captured_variables_with_context(
        replacement,
        captured_values,
        "Command output rewrite replacement",
    )?;
    let regex = Regex::new(pattern.as_str()).map_err(|err| {
        RenderError::Operational(format!("Invalid output rewrite pattern `{pattern}`: {err}"))
    })?;
    let generated_capture =
        generated_rewrite_capture_for_replace(rule, rendered, &regex, replacement.as_str())?;

    Ok(RewriteRuleResult {
        rendered: regex
            .replace_all(rendered, replacement.as_str())
            .into_owned(),
        generated_capture,
    })
}

fn apply_datetime_shift_rule(
    rule: &Value,
    rendered: &str,
    datetime_anchors: &mut HashMap<String, DatetimeShiftAnchor>,
) -> Result<RewriteRuleResult, RenderError> {
    let config = datetime_shift_config(rule)?;
    let regex = Regex::new(config.pattern).map_err(|err| {
        RenderError::Operational(format!(
            "Invalid output rewrite pattern `{}`: {err}",
            config.pattern
        ))
    })?;
    let base_timestamp = DateTime::parse_from_rfc3339(config.base).map_err(|err| {
        RenderError::Operational(format!(
            "Invalid datetime_shift base `{}`: {err}",
            config.base
        ))
    })?;
    let shared_anchor = match config.use_anchor {
        Some(anchor_id) => Some(datetime_anchors.get(anchor_id).ok_or_else(|| {
            RenderError::Operational(format!(
                "Command output datetime_shift uses unknown anchor `{anchor_id}`"
            ))
        })?),
        None => None,
    };
    let parse_reference_timestamp = shared_anchor
        .map(|anchor| anchor.base_timestamp)
        .unwrap_or(base_timestamp);

    let mut first_original: Option<DateTime<FixedOffset>> = None;
    let mut result = String::with_capacity(rendered.len());
    let mut last_end = 0;
    let mut capture_matches: Vec<(String, String)> = Vec::new();

    for matched in regex.find_iter(rendered) {
        result.push_str(&rendered[last_end..matched.start()]);
        let matched_text = matched.as_str().to_string();
        let original =
            parse_shift_datetime(&matched_text, config.matcher, parse_reference_timestamp)?;
        let shifted = match shared_anchor {
            Some(anchor) => anchor.shift(original),
            None => match first_original {
                Some(first) => shift_from_anchor(base_timestamp, first, original),
                None => {
                    first_original = Some(original);
                    base_timestamp
                }
            },
        };
        let rewritten_value = format_shift_datetime(shifted, config.matcher);
        if rule.get("capture_as").is_some() {
            capture_matches.push((matched_text, rewritten_value.clone()));
        }
        result.push_str(&rewritten_value);
        last_end = matched.end();
    }

    result.push_str(&rendered[last_end..]);

    if let (Some(anchor_id), Some(first_original)) = (config.anchor_id, first_original) {
        datetime_anchors.insert(
            anchor_id.to_string(),
            DatetimeShiftAnchor {
                first_original,
                base_timestamp,
            },
        );
    }

    Ok(RewriteRuleResult {
        rendered: result,
        generated_capture: generated_rewrite_capture_from_pairs(rule, capture_matches)?,
    })
}

fn apply_keep_between_rule(rule: &Value, rendered: &str) -> Result<RewriteRuleResult, RenderError> {
    let start = rule.get("start").and_then(Value::as_str).ok_or_else(|| {
        RenderError::Operational("Command output keep_between start must be a string".to_string())
    })?;
    let end = rule.get("end").and_then(Value::as_str);
    let start_offset = parse_keep_between_offset(rule.get("start_offset"), 1, "start_offset")?;
    let end_offset = parse_keep_between_offset(rule.get("end_offset"), -1, "end_offset")?;
    let show_trim_markers = parse_keep_between_show_trim_markers(rule.get("show_trim_markers"))?;

    let mut lines: Vec<&str> = rendered.split('\n').collect();
    if rendered.ends_with('\n') {
        lines.pop();
    }
    let Some(start_index) = lines.iter().position(|line| *line == start) else {
        return Ok(RewriteRuleResult {
            rendered: rendered.to_string(),
            generated_capture: None,
        });
    };
    let start_line = offset_index(start_index, start_offset, lines.len());
    let end_line = match end {
        Some(end) => {
            let Some(relative_end_index) =
                lines[start_index..].iter().position(|line| *line == end)
            else {
                return Ok(RewriteRuleResult {
                    rendered: rendered.to_string(),
                    generated_capture: None,
                });
            };
            let end_index = start_index + relative_end_index;
            offset_index(end_index, end_offset, lines.len())
        }
        None => lines.len().checked_sub(1),
    };

    let Some((start_line, end_line)) = start_line.zip(end_line) else {
        return Ok(RewriteRuleResult {
            rendered: String::new(),
            generated_capture: None,
        });
    };

    if start_line > end_line || start_line >= lines.len() || end_line >= lines.len() {
        return Ok(RewriteRuleResult {
            rendered: String::new(),
            generated_capture: None,
        });
    }

    let mut kept_lines: Vec<String> = lines[start_line..=end_line]
        .iter()
        .map(|line| (*line).to_string())
        .collect();
    if show_trim_markers {
        if start_line > 0 {
            kept_lines.insert(0, "...".to_string());
        }
        if end_line + 1 < lines.len() {
            kept_lines.push("...".to_string());
        }
    }

    Ok(RewriteRuleResult {
        rendered: kept_lines.join("\n"),
        generated_capture: None,
    })
}

fn parse_keep_between_offset(
    value: Option<&Value>,
    default: i64,
    key: &str,
) -> Result<i64, RenderError> {
    match value {
        None => Ok(default),
        Some(value) => value.as_i64().ok_or_else(|| {
            RenderError::Operational(format!(
                "Command output keep_between {key} must be an integer"
            ))
        }),
    }
}

fn parse_keep_between_show_trim_markers(value: Option<&Value>) -> Result<bool, RenderError> {
    match value {
        None => Ok(true),
        Some(value) => value.as_bool().ok_or_else(|| {
            RenderError::Operational(
                "Command output keep_between show_trim_markers must be a boolean".to_string(),
            )
        }),
    }
}

fn offset_index(index: usize, offset: i64, len: usize) -> Option<usize> {
    let shifted = index as i64 + offset;
    if shifted < 0 || shifted >= len as i64 {
        None
    } else {
        usize::try_from(shifted).ok()
    }
}

fn generated_rewrite_capture_for_replace(
    rule: &Value,
    rendered: &str,
    regex: &Regex,
    replacement: &str,
) -> Result<Option<RewriteCapturePair>, RenderError> {
    let Some(capture_as) = rule.get("capture_as").and_then(Value::as_str) else {
        return Ok(None);
    };

    let matches: Vec<String> = regex
        .find_iter(rendered)
        .map(|matched| matched.as_str().to_string())
        .collect();
    if matches.len() != 1 {
        return Err(RenderError::CommandFailed(format!(
            "Rewrite capture_as `{capture_as}` matched {} values; expected exactly one",
            matches.len()
        )));
    }

    let original_value = matches[0].clone();
    let rewritten_value = regex
        .replace(original_value.as_str(), replacement)
        .into_owned();

    Ok(Some(RewriteCapturePair {
        original_name: format!("{capture_as}_original"),
        original_value,
        rewritten_name: format!("{capture_as}_rewritten"),
        rewritten_value,
    }))
}

fn generated_rewrite_capture_from_pairs(
    rule: &Value,
    pairs: Vec<(String, String)>,
) -> Result<Option<RewriteCapturePair>, RenderError> {
    let Some(capture_as) = rule.get("capture_as").and_then(Value::as_str) else {
        return Ok(None);
    };

    if pairs.len() != 1 {
        return Err(RenderError::CommandFailed(format!(
            "Rewrite capture_as `{capture_as}` matched {} values; expected exactly one",
            pairs.len()
        )));
    }

    let (original_value, rewritten_value) = pairs.into_iter().next().expect("single pair");
    Ok(Some(RewriteCapturePair {
        original_name: format!("{capture_as}_original"),
        original_value,
        rewritten_name: format!("{capture_as}_rewritten"),
        rewritten_value,
    }))
}

struct DatetimeShiftConfig<'a> {
    pattern: &'a str,
    base: &'a str,
    matcher: DatetimeShiftMatcher<'a>,
    anchor_id: Option<&'a str>,
    use_anchor: Option<&'a str>,
}

#[derive(Clone, Copy)]
enum DatetimeShiftFormat {
    Rfc3339,
    Rfc1123,
}

#[derive(Clone, Copy)]
enum DatetimeShiftMatcher<'a> {
    BuiltIn(DatetimeShiftFormat),
    Custom(&'a str),
}

struct DatetimeShiftAnchor {
    first_original: DateTime<FixedOffset>,
    base_timestamp: DateTime<FixedOffset>,
}

impl DatetimeShiftAnchor {
    fn shift(&self, original: DateTime<FixedOffset>) -> DateTime<FixedOffset> {
        shift_from_anchor(self.base_timestamp, self.first_original, original)
    }
}

fn datetime_shift_config(rule: &Value) -> Result<DatetimeShiftConfig<'_>, RenderError> {
    let format = rule.get("format").and_then(Value::as_str);
    let pattern = rule.get("pattern").and_then(Value::as_str);
    let custom_format = rule.get("custom_format").and_then(Value::as_str);
    let base = rule
        .get("base")
        .and_then(Value::as_str)
        .unwrap_or(DEFAULT_DATETIME_SHIFT_BASE);
    let anchor_id = rule.get("id").and_then(Value::as_str);
    let use_anchor = rule.get("use").and_then(Value::as_str);

    if format.is_some() && pattern.is_some() {
        return Err(RenderError::Operational(
            "Command output datetime_shift must not include both format and pattern".to_string(),
        ));
    }

    if format.is_some() && custom_format.is_some() {
        return Err(RenderError::Operational(
            "Command output datetime_shift must not include both format and custom_format"
                .to_string(),
        ));
    }

    if anchor_id.is_some() && use_anchor.is_some() {
        return Err(RenderError::Operational(
            "Command output datetime_shift must not include both id and use".to_string(),
        ));
    }

    if use_anchor.is_some() && rule.get("base").is_some() {
        return Err(RenderError::Operational(
            "Command output datetime_shift that uses an anchor must not include base".to_string(),
        ));
    }

    let (pattern, matcher) = match (format, pattern, custom_format) {
        (Some("rfc3339"), None, None) => (
            RFC3339_PATTERN,
            DatetimeShiftMatcher::BuiltIn(DatetimeShiftFormat::Rfc3339),
        ),
        (Some("rfc1123"), None, None) => (
            RFC1123_PATTERN,
            DatetimeShiftMatcher::BuiltIn(DatetimeShiftFormat::Rfc1123),
        ),
        (Some(other), None, None) => {
            return Err(RenderError::Operational(format!(
                "Unsupported datetime_shift format `{other}`"
            )));
        }
        (None, Some(pattern), Some(custom_format)) => {
            (pattern, DatetimeShiftMatcher::Custom(custom_format))
        }
        (None, Some(_), None) => {
            return Err(RenderError::Operational(
                "Command output datetime_shift with pattern must include custom_format".to_string(),
            ));
        }
        (None, None, Some(_)) => {
            return Err(RenderError::Operational(
                "Command output datetime_shift custom_format requires pattern".to_string(),
            ));
        }
        (None, None, None) => {
            return Err(RenderError::Operational(
                "Command output datetime_shift must include either format or pattern".to_string(),
            ));
        }
        _ => unreachable!(),
    };

    Ok(DatetimeShiftConfig {
        pattern,
        base,
        matcher,
        anchor_id,
        use_anchor,
    })
}

fn parse_shift_datetime(
    value: &str,
    matcher: DatetimeShiftMatcher<'_>,
    base_timestamp: DateTime<FixedOffset>,
) -> Result<DateTime<FixedOffset>, RenderError> {
    match matcher {
        DatetimeShiftMatcher::BuiltIn(DatetimeShiftFormat::Rfc3339) => {
            DateTime::parse_from_rfc3339(value).map_err(|err| {
                RenderError::Operational(format!(
                    "Matched datetime `{value}` is not valid RFC 3339: {err}"
                ))
            })
        }
        DatetimeShiftMatcher::BuiltIn(DatetimeShiftFormat::Rfc1123) => {
            DateTime::parse_from_rfc2822(value).map_err(|err| {
                RenderError::Operational(format!(
                    "Matched datetime `{value}` is not valid RFC 1123: {err}"
                ))
            })
        }
        DatetimeShiftMatcher::Custom(custom_format) => {
            if let Ok(naive) = NaiveDateTime::parse_from_str(value, custom_format) {
                return base_timestamp
                    .offset()
                    .from_local_datetime(&naive)
                    .single()
                    .ok_or_else(|| {
                        RenderError::Operational(format!(
                            "Matched datetime `{value}` could not be interpreted with offset {}",
                            base_timestamp.offset()
                        ))
                    });
            }

            let time = NaiveTime::parse_from_str(value, custom_format).map_err(|err| {
                RenderError::Operational(format!(
                    "Matched datetime `{value}` does not match custom_format `{custom_format}`: {err}"
                ))
            })?;
            let naive = base_timestamp.date_naive().and_time(time);
            base_timestamp
                .offset()
                .from_local_datetime(&naive)
                .single()
                .ok_or_else(|| {
                    RenderError::Operational(format!(
                        "Matched datetime `{value}` could not be interpreted with offset {}",
                        base_timestamp.offset()
                    ))
                })
        }
    }
}

fn format_shift_datetime(
    datetime: DateTime<FixedOffset>,
    matcher: DatetimeShiftMatcher<'_>,
) -> String {
    match matcher {
        DatetimeShiftMatcher::BuiltIn(DatetimeShiftFormat::Rfc3339) => {
            datetime.to_rfc3339_opts(chrono::SecondsFormat::Millis, true)
        }
        DatetimeShiftMatcher::BuiltIn(DatetimeShiftFormat::Rfc1123) => {
            datetime.format("%a, %d %b %Y %H:%M:%S GMT").to_string()
        }
        DatetimeShiftMatcher::Custom(custom_format) => {
            datetime.naive_local().format(custom_format).to_string()
        }
    }
}

fn shift_from_anchor(
    base_timestamp: DateTime<FixedOffset>,
    anchor_original: DateTime<FixedOffset>,
    original: DateTime<FixedOffset>,
) -> DateTime<FixedOffset> {
    let delta = original - anchor_original;
    base_timestamp
        + Duration::seconds(delta.num_seconds())
        + Duration::nanoseconds(
            (delta - Duration::seconds(delta.num_seconds()))
                .num_nanoseconds()
                .unwrap_or(0),
        )
}

fn trim_trailing_whitespace(output: &Value) -> Result<bool, RenderError> {
    match output.get("trim_trailing_whitespace") {
        Some(Value::Bool(value)) => Ok(*value),
        Some(_) => Err(RenderError::Operational(
            "Command output trim_trailing_whitespace must be a boolean".to_string(),
        )),
        None => Ok(true),
    }
}

fn trim_segment_trailing_whitespace(segment: &str) -> String {
    let has_newline = segment.ends_with('\n');
    let body = if has_newline {
        &segment[..segment.len() - 1]
    } else {
        segment
    };
    let trimmed = body.trim_end_matches(char::is_whitespace);

    if has_newline {
        format!("{trimmed}\n")
    } else {
        trimmed.to_string()
    }
}

fn display_file_content_type(path: &Path) -> &'static str {
    match path.extension().and_then(|extension| extension.to_str()) {
        Some("java") => "java",
        _ => "text",
    }
}

fn apply_indent(entry: &Value, section: String) -> Result<String, RenderError> {
    let Some(indent) = entry.get("indent") else {
        return Ok(section);
    };

    let indent_width = match (indent.as_u64(), indent.as_i64()) {
        (Some(width), _) => usize::try_from(width)
            .map_err(|_| RenderError::Operational("Command indent is too large".to_string()))?,
        (None, Some(width)) if width >= 0 => usize::try_from(width)
            .map_err(|_| RenderError::Operational("Command indent is too large".to_string()))?,
        _ => {
            return Err(RenderError::Operational(
                "Command indent must be a non-negative integer".to_string(),
            ));
        }
    };

    if indent_width == 0 {
        return Ok(section);
    }

    let prefix = " ".repeat(indent_width);
    Ok(section
        .lines()
        .map(|line| {
            if line.is_empty() {
                String::new()
            } else {
                format!("{prefix}{line}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n"))
}

fn combine_messages(primary: &str, secondary: Option<&str>) -> String {
    match secondary {
        Some(secondary) => format!("{primary}\n{secondary}"),
        None => primary.to_string(),
    }
}
